### ISSUE TITLE
Error Installaling

### ISSUE THREAD

**Issue by OpenAlgeria** [Plume-org/Plume#100]
Error on command line 

`cargo run`

> 

>  Compiling rand v0.4.2
>    Compiling memchr v2.0.1
>    Compiling time v0.1.40
>    Compiling isatty v0.1.8
>    Compiling rpassword v2.0.0
>    Compiling tokio-executor v0.1.2
>    Compiling tokio-service v0.1.0
>    Compiling relay v0.1.1
>    Compiling proc-macro2 v0.4.6
>    Compiling openssl-sys v0.9.33
>    Compiling backtrace-sys v0.1.23
> error[E0433]: failed to resolve. Could not find `Punct` in `proc_macro`
>    --> /home/blog/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.6/src/unstable.rs:131:42
>     |
> 131 |                 let mut op = proc_macro::Punct::new(tt.as_char(), spacing);
>     |                                          ^^^^^ Could not find `Punct` in `proc_macro`
> 
> error[E0433]: failed to resolve. Could not find `Ident` in `proc_macro`
>    --> /home/blog/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.6/src/unstable.rs:468:60
>     |
> 468 |             Span::Nightly(s) => Ident::Nightly(proc_macro::Ident::new(string, s)),
>     |                                                            ^^^^^ Could not find `Ident` in `proc_macro`
> 
> error[E0433]: failed to resolve. Could not find `Ident` in `proc_macro`
>    --> /home/blog/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.6/src/unstable.rs:475:60
>     |
> 475 |             Span::Nightly(s) => Ident::Nightly(proc_macro::Ident::new_raw(string, s)),
>     |                                                            ^^^^^ Could not find `Ident` in `proc_macro`
> 
> error[E0412]: cannot find type `Ident` in module `proc_macro`
>    --> /home/blog/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.6/src/unstable.rs:461:25
>     |
> 461 |     Nightly(proc_macro::Ident),
>     |                         ^^^^^ not found in `proc_macro`
> help: possible candidates are found in other modules, you can import them into scope
>     |
> 3   | use Ident;
>     |
> 3   | use imp::Ident;
>     |
> 3   | use stable::Ident;
>     |
> 
> error[E0412]: cannot find type `Ident` in module `proc_macro`
>    --> /home/blog/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.6/src/unstable.rs:495:44
>     |
> 495 |     fn unwrap_nightly(self) -> proc_macro::Ident {
>     |                                            ^^^^^ not found in `proc_macro`
> help: possible candidates are found in other modules, you can import them into scope
>     |
> 3   | use Ident;
>     |
> 3   | use imp::Ident;
>     |
> 3   | use stable::Ident;
>     |
> 
>    Compiling ring v0.13.0-alpha5
>    Compiling gettext-sys v0.19.8
>    Compiling serde v1.0.68
>    Compiling num-traits v0.2.5
> error[E0599]: no function or associated item named `new` found for type `proc_macro::TokenStream` in the current scope
>   --> /home/blog/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.6/src/unstable.rs:45:34
>    |
> 45 |             TokenStream::Nightly(proc_macro::TokenStream::new())
>    |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `proc_macro::TokenStream`
> 
> error[E0599]: no variant named `Punct` found for type `proc_macro::TokenTree` in the current scope
>    --> /home/blog/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.6/src/unstable.rs:250:13
>     |
> 250 |             proc_macro::TokenTree::Punct(tt) => {
>     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ variant not found in `proc_macro::TokenTree`
> 
> error[E0599]: no variant named `Ident` found for type `proc_macro::TokenTree` in the current scope
>    --> /home/blog/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.6/src/unstable.rs:259:13
>     |
> 259 |             proc_macro::TokenTree::Ident(s) => ::Ident::_new(Ident::Nightly(s)).into(),
>     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ variant not found in `proc_macro::TokenTree`
> 
> error: aborting due to 8 previous errors
> 
> Some errors occurred: E0412, E0433, E0599.
> For more information about an error, try `rustc --explain E0412`.
> error: Could not compile `proc-macro2`.
> warning: build failed, waiting for other jobs to finish...
> error: build failed
> 
> 
> `

**Comment by BaptisteGelez** [comment]
Hello! Did you installed Rust with Rustup? And can you please give me the output of `rustc --version`? Thanks!

**Comment by OpenAlgeria** [comment]
Thank you for your reply 

`rustc 1.28.0-nightly (e3bf634e0 2018-06-28)
`

**Comment by gled-rs** [comment]
Did you try rustup override set nightly-2018-05-15 ?

It helped when I was installing.

**Comment by OpenAlgeria** [comment]
Yes I tried , But still the same error  :(

**Comment by gled-rs** [comment]
And if you switch to nightly-2018-05-30 ?

This is the one I am currently on.

**Comment by OpenAlgeria** [comment]
> error: failed to run custom build command for `rocket_codegen v0.4.0-dev (https://github.com/SergioBenitez/Rocket?rev=df7111143e466c18d1f56377a8d9530a5a306aba#df711114)`
> process didn't exit successfully: `/home/plume/blog/target/debug/build/rocket_codegen-40740214c54312f9/build-script-build` (exit code: 101)
> --- stderr
> Error: Rocket codegen requires a more recent version of rustc.
> Use `rustup update` or your preferred method to update Rust.
> Installed version is: 1.28.0-nightly (2018-05-29). Minimum required: 1.28.0-nightly (2018-05-30).
> thread 'main' panicked at 'Aborting compilation due to incompatible compiler.', /home/plume/.cargo/git/checkouts/rocket-8bf16d9ca7e90bdc/df71111/core/codegen/build.rs:50:17
> note: Run with `RUST_BACKTRACE=1` for a backtrace.
> 
> warning: build failed, waiting for other jobs to finish...
>

**Comment by OpenAlgeria** [comment]
I solved the problem 
I"m switch to nightly-2018-05-31

Thanks you @gled-rs
