### ISSUE TITLE
"Work In Progress" Management / Drafts

### ISSUE THREAD

**Issue by marseye** [Plume-org/Plume#102]
Hello,

Being a simple user at https://Mastodon.host, which hosts too a bunch of other services, of which Plume (https://plume.mastodon.host), I just went for a quick test. Adressing a request to my admin (he's an incredible one), he told me to submit an issue to you, and that you "are nice to speak with", I now just hope that I'm here at the right place for my request.

In substance, I had told this (sorry, not my native language):
There's no "Work-In -Progress" backup : it's "publish or lose it"... So any WIP, at worst, must be published... We'd better prepare our articles somewhere else. Though I can understand why such limitation ("it's a publishing tool, not your average notepad"), It feels not very handy. We could have up to 5 WIP for example (even 1 only ; I understand that previewing 'often' might yield a risk of intensive server charge). So, Is it planned somehow ?

I yet haven't had the time to check the Markdown integration extents, but I'll give it a mild try too.

Thank you for your time, dedication and already great work.

**Comment by BaptisteGelez** [comment]
Hello! Yes, you're at the right place for your suggestion.

I plan to introduce drafts/WIP articles, but maybe not in the first alpha (but there are chances they'll be here for the first official release). However, I would like to know, why you would want to only have a limited number of them?

Thanks for your time too!

**Comment by marseye** [comment]
I wouldn't really wish any drafts limit. 

I definitly was just  beging for at least better than the zero drafts capabilities that I suffered with the test instance that I could try ;) Your reply answers certainly my request's concern. 

But I said that I would perfectly understand that some admins could want to benefit of an opportunity to preserve some of their server's storage ressources, having to possibbly deal with abusive users, like those who feel everywhere like at home, especially when it's free storage.  In the fediverse, private individuals's servers investments are not to be discouraged. That's where the possibility of an arbitrary number of drafts limit could reveal interesting for some, more than a max allowable storage by user. But maybe I'm anticipating too much, though for the benefice of others.

But Thank you ;) and for you replied fast.

**Comment by BaptisteGelez** [comment]
Hum… I think I will implement the possibility to limit the data stored by user or the number of drafts, but I think it will be disabled by default.
