### ISSUE TITLE
Some comments are duplicated

### ISSUE THREAD

**Issue by BaptisteGelez** [Plume-org/Plume#113]
If you look at https://baptiste.gelez.xyz/~/PlumeDevelopment/this-month-in-plume-june-2018/ it seems to happen especially on comments with multiple mentions.

**Comment by BaptisteGelez** [comment]
May be related to #80 too

**Comment by ffffluffy** [comment]
It seems I'm one of the users affected by this duplication bug.

Comment without mention :
  * https://baptiste.gelez.xyz/~/Announcements@blog.funkwhale.audio/funkwhale-past-present-and-future/
  * https://baptiste.gelez.xyz/~/Testmiraty/ben-voila/
  * https://baptiste.gelez.xyz/~/FluffysTests/this-is-a-media-test/
  * https://baptiste.gelez.xyz/~/FluffysAdventures/writing-prompts-the-desert's-shadow/

Comment with one mention :
  * https://baptiste.gelez.xyz/~/Plume/plume/
  * Here, it affects also @ 0x1C3B00DA https://baptiste.gelez.xyz/~/MakeBlogPhoe/how-does-one-use-activity-pub-for-games/

However, here for example, I don't have any duplication : https://baptiste.gelez.xyz/~/Nguy%C3%AAn/test-blog-post-1/

**Comment by BaptisteGelez** [comment]
Thanks for investigating this!

**Comment by BaptisteGelez** [comment]
I think it happens when someone from the same Plume instance follows you.

**Comment by fdb-hiroshima** [comment]
There are still issues with duplicated comments [here](https://baptiste.gelez.xyz/~/PlumeDevelopment/plume's-first-release/#comment-502). The comment appear 3 times, and conveniently that's also the number of peoples from the Plume instance who got mentioned. However this comment was originated from Mastodon

**Comment by BaptisteGelez** [comment]
@fdb-hiroshima I guess Mastodon sent it to each users' inbox, running thrice the creation code in Plume.

**Comment by fdb-hiroshima** [comment]
Closed by #342
