### ISSUE TITLE
Links in title are not visible enough

### ISSUE THREAD

**Issue by BaptisteGelez** [Plume-org/Plume#120]
Unless you move your cursor over them, it is not obvious they are links.

**Comment by fdb-hiroshima** [comment]
Are links allowed in post titles? Titles are not rendered with md, nor are they `SafeString`s at the moment

**Comment by BaptisteGelez** [comment]
No, I mean on article listings, the title of the article is a link, but it may be hard to understand it is.

However, looking back at this issue I'm not sure it is valid: it seems quite obvious these titles are link to the article… Maybe we should just close it?
