### ISSUE TITLE
Underline links

### ISSUE THREAD

**Issue by BaptisteGelez** [Plume-org/Plume#140]
In the articles, to make it clear they are links. Maybe we can also underline them in other places, but only when the cursor is over them.

**Comment by bitkeks** [comment]
The solution in a82cccf feels pretty hacky. 
I tried injecting the icon into the Markdown parser in https://github.com/Plume-org/Plume/blob/b1c1ba151dcd84ef18d5d05be50a848dafef0abe/plume-common/src/utils.rs#L27-L29

by using another `match` like below. But this doesn't manipulate the link, only the title text :man_facepalming: 
```rust
Event::Start(tag) => {
    let tag = match tag {
        Tag::Link(url, title) => {
            let appended_icon: &str = "<i class=\"fas fa-external-link-alt\"></i>";
            Tag::Link(url, title + appended_icon)
        },
        _ => tag
    };
    ...
}
```
