### ISSUE TITLE
"New article" button leads to wrong url

### ISSUE THREAD

**Issue by Alienglyph** [Plume-org/Plume#160]
After starting a new blog on the demo instance the "New article" button led me to

"https://baptiste.gelez.xyz/~/new" which doesn't exist

Changing it manually to "https://baptiste.gelez.xyz/~/NameOfBlog/new" fixed it ;-)

**Comment by BaptisteGelez** [comment]
It should have been fixed with b42030e. Feel free to re-open this issue if the problem persists.
