### ISSUE TITLE
Consider using askama for templates

### ISSUE THREAD

**Issue by BaptisteGelez** [Plume-org/Plume#161]
[Askama](https://github.com/djc/askama) is a templating library that compiles templates into native Rust code. It means that templates are type-checked, and that you can use macros like `uri!` inside of them, which could be really useful.

**Comment by BaptisteGelez** [comment]
Since we are using Rocket 0.4, and askama Rocket 0.3, we can consider this as blocked until Rocket 0.4 is officially released and askama supports it.

**Comment by fdb-hiroshima** [comment]
I think this has been supersede by Ructe
