### ISSUE TITLE
Language request, please add galician.

### ISSUE THREAD

**Issue by xmgz** [Plume-org/Plume#165]
I'd like to contribute to plume translating it to galician.

As requested here
https://github.com/Plume-org/Plume/blob/master/INTERNATIONALIZATION.md
I'm have not a "devlopment enviroment" so please could anyone here add my language to /po/LINGUAS?

It's galician, "gl" language code.

Then I'll PR the translated files to the project, thanks in advance ;)

p.d: I dont know how to add labels to this issue for better issue management. Sorry.

**Comment by BaptisteGelez** [comment]
I don't have much time this week, but I'll try to add it on Sunday if nobody does it before.

**Comment by BaptisteGelez** [comment]
Sorry, I added it a bit later than I expected, but better late than never.
