### ISSUE TITLE
Use the activitystreams crate

### ISSUE THREAD

**Issue by BaptisteGelez** [Plume-org/Plume#17]
This crate looks amazing, and I'm sure we would benefit from using it: https://github.com/asonix/activitystreams

**Comment by asonix** [comment]
Woah hey

That's not ready for use yet but I'm hoping to get work done on it today

There's so much redundancy in there and it isn't extensible yet

**Comment by asonix** [comment]
But thanks for taking a look at it :3 I'm glad it looks promising

**Comment by asonix** [comment]
I've released version 0.1.0 of ActivityStreams!

Take a look and see what you think

**Comment by asonix** [comment]
I've released version 0.1.0 of ActivityStreams!

Take a look and see what you think!

https://github.com/asonix/activitystreams/releases/tag/v0.1.0

**Comment by BaptisteGelez** [comment]
Amazing! I will have a look at it today or tomorrow I think. Thanks for your work!
