### ISSUE TITLE
Following mastodon users won't work

### ISSUE THREAD

**Issue by ffffluffy** [Plume-org/Plume#172]
Using my Plume account (fluffy@baptiste.gelez.xyz), I tried to follow my main mastodon account, fluffy@eldritch.cafe, as well as another public account (poutounu@catboy.cafe), and on the Plume interface, it said I followed these accounts, but from mastodon, it doesn't seem so.

I guess there is a federating problem for follows with mastodon. (But a mastodon account can still follow a Plume one.)

**Comment by ffffluffy** [comment]
Maybe this is a broader federation problem. I tried to mention fluffy@eldritch.cafe from a plume comment and got no notification on mastodon, nor any toot is displayed from fluffy@baptiste.gelez.xyz seen by the mastodon interface at eldritch.cafe. (The comment in question : https://baptiste.gelez.xyz/~/FluffysTests/hey-this-is-a-test#comment-301)

**Comment by BaptisteGelez** [comment]
It is because Mastodon is doing weird things with AP `Collection`s, not directly listing `items` but redirecting to other pages instead…

**Comment by BaptisteGelez** [comment]
I checked the spec, and it looks like Mastodon is actually right here…
