### ISSUE TITLE
Disfunctioning of rss feeds

### ISSUE THREAD

**Issue by maximesrd** [Plume-org/Plume#192]
The rss feed of each blog does not work.

When the user  subscribes to the rss feed of the blogger, it works:
![capture du 2018-09-03 21-27-59](https://user-images.githubusercontent.com/42911617/44999809-41f5a780-afc0-11e8-9200-37ea9ece9188.png)

When the user subscribes to the rss feed of the blog, it doesn't work:
![capture du 2018-09-03 21-29-33](https://user-images.githubusercontent.com/42911617/44999837-7701fa00-afc0-11e8-814c-3b22112c0373.png)

**Comment by BaptisteGelez** [comment]
It is because the link is broken. It should work if you replace the `@` in the URL with a `~`.
