### ISSUE TITLE
Markdown ?

### ISSUE THREAD

**Issue by marseye** [Plume-org/Plume#198]
Hi Baptiste,

Just tried there to make use of a link Markdown syntax, but it didn't work as intended. See there : https://plume.mastodon.host/~/InsideOfMe/plume-s'am%C3%A9liore/  (I tried to link this github).

Though, Plume states (in the article composer mode) that Markdown can be used. So ?

[Otherwise : thanks for we now can delete an article ;) That's not naught: it was highly needed.]

**Comment by BaptisteGelez** [comment]
@fdb-hiroshima is right, it didn't worked because there was a space between the `]` and the `(`.

**Comment by marseye** [comment]
You are right... I feel terrible... Sorry for my lack of faith. Thank you all.
