### ISSUE TITLE
Several "graphical bugs"

### ISSUE THREAD

**Issue by maximesrd** [Plume-org/Plume#199]
Hello!
For users who do not have a profile picture, it would be nicer to put "my profile" on a single line.
![capture du 2018-09-05 15-20-09](https://user-images.githubusercontent.com/42911617/45110283-24504b80-b142-11e8-94f3-8eb512aae0ad.png)

and there's a small problem with usernames that are too long: 
![screenshot-2018-9-5 lenbyanargeek plume](https://user-images.githubusercontent.com/42911617/45110413-742f1280-b142-11e8-9c48-77b0b227352a.png)

**Comment by xmgz** [comment]
when user's avatar is not set, the default image
>GET https://fediverse.blog/static/default-avatar.png 404

is not in the expected url (or not available there).


Should I open a new "issue"? or is it fine here bc is a "graphical bug"?

**Comment by BaptisteGelez** [comment]
I would prefer another issue, please. Actually the issue is that we don't have a default avatar yet, not even that the URL is incorrect…

**Comment by BaptisteGelez** [comment]
@maximesrd I fixed your second issue, but for the first one there was no clean fix (the only solution breaks valid avatars), so I centered the text to make it a bit nicer, but it is far from perfect… :confused:
