### ISSUE TITLE
Shared inboxes

### ISSUE THREAD

**Issue by BaptisteGelez** [Plume-org/Plume#20]

**Comment by lthms** [comment]
Out of curiosity, what do you call `shared inboxes`?

**Comment by BaptisteGelez** [comment]
As you may know activities are delivered to various inboxes depending on the visibility of the message/article/whatever you send (it may only be your followers' inboxes, mentioned people's ones, or any known inbox in the case of a public activity). But it means that you may send the same activity to the same server twice (or even more, if there are 100 people following you on one instance, the activity would be sent 100 times, to each follower's inbox), so to avoid spamming the ActivityPub spec says that an actor may have a "sharedInbox" property, which is the URL of an inbox for the whole instance. This way, an activity is only sent once to each instance.

I started implementing it (I just need to check it is working fine actually, but it should), you can see the changes with these three commits: https://github.com/Plume-org/Plume/commit/fdc481e384f619e9fb5e4fd1d588b01ecfe077f5 https://github.com/Plume-org/Plume/commit/dfab0290e4b2ddc73d1593124a2cb3f6643cf04c and https://github.com/Plume-org/Plume/commit/9c9799eee254fdcd80a25a5f2f29fa6b7a4deca7

Reference: https://www.w3.org/TR/activitypub/#sharedInbox
