### ISSUE TITLE
Duplicated instances

### ISSUE THREAD

**Issue by maximesrd** [Plume-org/Plume#201]
I was surprised at the number of federated instances : 
![screenshot-2018-9-6 about le blog d un e enby anar geek plume](https://user-images.githubusercontent.com/42911617/45177336-eec76300-b212-11e8-8ebe-3ba465da371b.png)

In the database, some instances are duplicated:

 `SELECT * FROM "instances"`
![screenshot-2018-9-6 selectionner instances - 127 0 0 1 - adminer](https://user-images.githubusercontent.com/42911617/45177226-a5771380-b212-11e8-850a-a41654d9282b.png)

**Comment by BaptisteGelez** [comment]
Do you have the same instance more than twice sometimes?

**Comment by maximesrd** [comment]
Nope, only twice times
