### ISSUE TITLE
The editor doesn't work

### ISSUE THREAD

**Issue by maximesrd** [Plume-org/Plume#204]
Hello,
I wanted to edit a blog post with the editor (recently appeared:)) but it's totally empty instead of having the content to edit.

Article: 

![screenshot-2018-9-7 mon materiel plume](https://user-images.githubusercontent.com/42911617/45243250-61a80b00-b2f3-11e8-89e3-0c7295aa389a.png)

Editor:
![screenshot-2018-9-7 modifier mon materiel plume](https://user-images.githubusercontent.com/42911617/45243261-6cfb3680-b2f3-11e8-9bd9-21e9f037c05e.png)
![screenshot-2018-9-7 modifier mon materiel plume 1](https://user-images.githubusercontent.com/42911617/45243292-856b5100-b2f3-11e8-88e1-47f35d567e0c.png)

**Comment by BaptisteGelez** [comment]
Yes, editing posts created before this feature was introduced won't work, I'm sorry… the markdown was not stored before, only the resulting HTML, so we can't get it back… :confused:

**Comment by ffffluffy** [comment]
I'm sorry to interject, but couldn't we edit the HTML then, by setting that the markdown is the html if there is no markdown before ?
Anyway, this is not a big issue, as it will work with all future posts.

**Comment by BaptisteGelez** [comment]
@ffffluffy good idea, I didn't thought about it. I just hope that it won't be too confusing…
