### ISSUE TITLE
Update without script

### ISSUE THREAD

**Issue by anmol26s** [Plume-org/Plume#209]
Hi
I would like to upgrade without git as mentioned here https://github.com/Plume-org/Plume/blob/master/docs/UPDATE.md.

So I would like to : 
1. Backup the important files and folders like .env, etc.
2. Delete the the source folder
3. Download and decompress the fresh sources to the folder.
4. Restore the importation files and folders like .env to the new unpacked sources.

So for this I would like to know what files and folders are needed to be backed up and needs to be restored to the newly unpacked sources, so that the Plume don't break.

**Comment by BaptisteGelez** [comment]
The only configuration file is the `.env`, everything else is stored in the DB, or will be generated by Plume at runtime (translations). If you write a Bash script to make this update automatic, please share it there, it could be useful to other persons (but there is no problem if you don't).

**Comment by BaptisteGelez** [comment]
Wow, great! For the systemd issue, if I understand correctly `__FINAL_PATH__` is the path where Plume will be installed, right? Then, replacing

```
ExecStart=__FINALPATH__/ cargo run >> /var/log/__APP__/__APP__.log 2>&1
```

by

```
ExecStart=cargo run >> /var/log/__APP__/__APP__.log 2>&1
```

May work, I think, since there is no reason this path appears here. But I may be wrong. :man_shrugging:

**Comment by anmol26s** [comment]
>  if I understand correctly __FINAL_PATH__ is the path where Plume will be installed, right?

yes you are right the __FINAL_PATH__ is the directory where Plume is installed.
I have already tried ExecStart=cargo run, but its not working? Any other advise?

**Comment by anmol26s** [comment]
ExecStart=cargo run gives me error at the end of the complie:

`error: linking with `cc` failed: exit code: 1`

**Comment by BaptisteGelez** [comment]
Do you have any other error message before that?

**Comment by BaptisteGelez** [comment]
We recently updated the Rust Nightly we are using, you should re-try after updating to the version specified in the `rust-toolchain` file.

**Comment by anmol26s** [comment]
Ok thanks
The build work now. But the diesel building by this command:
`cargo install diesel_cli --no-default-features --features postgres --version '=1.2.0'`

Gives a warning : 
`warning: be sure to add /root/.cargo/bin to your PATH to be able to run the installed binaries`

and migration is not working because it says  **diesel: command not found**

**Comment by BaptisteGelez** [comment]
Is `/root/.cargo/bin` in the `PATH`? I guess the warning is shown because it is not.

**Comment by anmol26s** [comment]
How can I add `/root/.cargo/bin` to the `PATH` if its not there?

**Comment by BaptisteGelez** [comment]
You can either replace `diesel` with `/root/.cargo/bin/diesel`, or do something like `export PATH=$PATH:/root/.cargo/bin`.

**Comment by anmol26s** [comment]
Ok thanks
The `cargo run` ask for a password at the start. What is this for ?
```
Welcome in the Plume setup tool.
It will help you setup your new instance, by asking you a few questions.
Then you'll be able to enjoy Plume!

First let's check that you have all the required dependencies. Press Enter to start.

```
Can I put these values in a file by default so that these questions which are asked at the first time are not asked and the values are taken from the file by itself?

**Comment by BaptisteGelez** [comment]
Well, not really. If this script starts, it is because Plume was not able to find a valid database, however by looking at the script you wrote, I can see you set it up correctly, so I think you just need to tell Plume where it is, by setting this environment variable:

```
DB_URL=postgres://$db_name:$db_pwd@localhost:5432/plume
```

before running `cargo run`.

**Comment by anmol26s** [comment]
yes I am the script needs  `export PATH=$PATH:/root/.cargo/bin`

The `cargo run `gives me this error but it works:
```
Error: missing configuration key: 'template_dir'
    => Warning: Using default templates directory '"/var/www/plume/templates"'

```

I request you publish pre-release of the Plume, so that its easy to manage the sources in Yunohost.

**Comment by BaptisteGelez** [comment]
I planned to publish one in the following days, I have a few issues to fix before. Is it possible for you to wait a little bit (if not, I can do a pre-pre-release)?

**Comment by anmol26s** [comment]
of course I can wait :+1:

**Comment by BaptisteGelez** [comment]
@anmol26s I just released the first alpha. Here is the GitHub release if you want: https://github.com/Plume-org/Plume/releases/tag/0.2.0-alpha-1

**Comment by anmol26s** [comment]
Thanks for the Alpha release. 

I am getting error while build.

 ```
Compiling tokio-core v0.1.17
3594402 WARNING error: linking with `cc` failed: exit code: 1
3594402 WARNING   |
3594658 WARNING   = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/root/.rustup/toolchains/nightly-2018-07-17-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/var/www/plume/target/debug/deps/rocket_codegen-b0f76ae28e83f6f8.rocket_codegen0.rcgu.o" "/var/www/plume/target/debug/deps/rocket_c
```

**Comment by BaptisteGelez** [comment]
The setup script have been removed and replaced with "real" CLI tools (e.g you can give them arguments).
