### ISSUE TITLE
Error: environment variable 'secret_key… could not be parsed

### ISSUE THREAD

**Issue by igalic** [Plume-org/Plume#218]
when trying to `cargo run` this project with

```sh
ROCKET_SECRET_KEY=4biIRCA6FL2RWqfPF6WGCniLQECKzC4VvVM5tVw/3OGxjbuEn51RAolDGYNK
```

set, i'm running into the following error:

```
Error: environment variable 'secret_key=4biIRCA6FL2RWqfPF6WGCniLQECKzC4VvVM5tVw/3OGxjbuEn51RAolDGYNK' could not be parsed
    => expected a 256-bit base64 encoded string, but found string
```

**Comment by fdb-hiroshima** [comment]
As said in the error message, your secret key is not of the right size. Yours is 60 base64 char long, which is 45Bytes or 360bits, where the expected one should be 32Bytes/256bits, which is roughly 45 base64 characters. On Linux based system you can generate a key by running `openssl rand -base64 32`, or you can let Plume generate one at it's first run
