### ISSUE TITLE
Please do not rely on a nightly build of Rust.

### ISSUE THREAD

**Issue by wimvanderbauwhede** [Plume-org/Plume#22]
Is it really necessary to rely on a nightly build of Rust? I'm afraid this will put many people off. 
Please consider making it work with the latest released version instead. Thank you!

**Comment by zxvfxwing** [comment]
Yes indeed, Rocket needs nightly.

They are working on it to bring Rocket on stable channel.
You can track the [issue](https://github.com/SergioBenitez/Rocket/issues/19)

**Comment by BaptisteGelez** [comment]
And normally, if you set up Rust with rustup, the nightly version will be used automatically, but only for Plume.

**Comment by wimvanderbauwhede** [comment]
I closed it, what's the point anyway.
