### ISSUE TITLE
Broken profile image?

### ISSUE THREAD

**Issue by Serkan-devel** [Plume-org/Plume#222]
![2018-09-14-142101_1600x900_scrot](https://user-images.githubusercontent.com/16866642/45549872-850a1300-b829-11e8-836a-7de258234618.png)
https://fediverse.blog/~/PlumeDevelopment@baptiste.gelez.xyz/plume-needs-a-logo/

**Comment by BaptisteGelez** [comment]
I cant' reproduce. Which browser and OS are you using please?

**Comment by Serkan-devel** [comment]
`68.0.3440.75 (Entwickler-Build) built on Debian buster/sid, running on Debian buster/sid (64-Bit)`

**Comment by Serkan-devel** [comment]
While just typing https://fediverse.blog/ now gives me an error code 500

**Comment by Serkan-devel** [comment]
@BaptisteGelez only the root directory doesn't seem to work. If I want to view individual blogs, I still can
