### ISSUE TITLE
Broken link on user page

### ISSUE THREAD

**Issue by roipoussiere** [Plume-org/Plume#227]
Just after my registration on https://fediverse.blog, I created a new blog. Then, when I click on the blog name on the top-left corner, (pointing to https://fediverse.blog/~/), I got a *page not found* error.

**Comment by BaptisteGelez** [comment]
You were on the blog page when clicking this link? And what was the name of your blog?

**Comment by roipoussiere** [comment]
To reproduce:

1. create a new blog, ie. `Test`
2. click on the `Test` link on the top left corner. You can see the this button points to https://fediverse.blog/~/ and not to https://fediverse.blog/~/test.
3. enjoy the 404 page.

**Comment by Atul9** [comment]
@BaptisteGelez I have opened up a PR for this #242
