### ISSUE TITLE
Feature request: single user mode

### ISSUE THREAD

**Issue by jeroenpraat** [Plume-org/Plume#241]
Right now Plume is aimed towards multiple users on one instance. It would be great if there's a single user mode.

This would actually mean that the root of the (sub)domain (https://blog.example.com) would show a specific blog instead of Plume's landing page.

Plume version (and/or commit): 0.2.0

**Comment by BaptisteGelez** [comment]
Hello!

I consider this issue a duplicate of #94, please re-open if what the implementation I proposed there is not correctly covering your use case.
