### ISSUE TITLE
User summary has no markdown support, but allows html

### ISSUE THREAD

**Issue by igalic** [Plume-org/Plume#247]
when entering a summary to `http://0.0.0.0:7878/@/:user/edit` that Summary cannot be Markdown.

However, it will accept html… which seems to be normalized:

```
Homoiconic ops witch<br/>Disappointing expectations since 1894.
```

becomes:

```html
<div class="user-summary">
    Homoiconic Ops Witch<br>Disappointing Expectations since 1894.
</div>
```

**Comment by BaptisteGelez** [comment]
Yes, this field should allow Markdown.

**Comment by igalic** [comment]
is there a reason why we don't just make every input string a SafeString?

**Comment by BaptisteGelez** [comment]
SafeString is only for content that may contain HTML, as the role of this type is to make sure dangerous tags get removed before saving them. Articles titles for instance, should never contain any particular tag, so `String` is the appropriate type. Both `SafeString` and `String` are escaped by Tera unless we add the `safe` filter, so there is no risk to use `String`s directly (but you should never use `| safe` on them).

**Comment by igalic** [comment]
isn't this fixed by now?

**Comment by BaptisteGelez** [comment]
No, still no markdown support here if I remember correctly.
