### ISSUE TITLE
Fallback to username if no display name is available

### ISSUE THREAD

**Issue by BaptisteGelez** [Plume-org/Plume#25]
For instance, nothing is displayed here: https://baptiste.gelez.xyz/~/MonBlog/plume-development-comments-are-coming/#comment-54

**Comment by JosephKiranBabu** [comment]
It is currently possible to create accounts without any usernames. The system seems to be already falling back to usernames when no display name is set.

I was able to reproduce this by creating an account without a username. I only gave email and password in the registration form. Then I was able to create nameless comments just like those in the demo instance. I think the correct solution here is to disallow creating accounts without usernames.

**Comment by BaptisteGelez** [comment]
> It is currently possible to create accounts without any usernames.

Yes, but it is a different problem.

> The system seems to be already falling back to usernames when no display name is set.

I can confirm it's not. :sweat_smile:

**Comment by BaptisteGelez** [comment]
Closed in #50
