### ISSUE TITLE
Improve ActivityPub delivery

### ISSUE THREAD

**Issue by BaptisteGelez** [Plume-org/Plume#252]
When sending activities to a lot of other inboxes, we currently have two problems:

- some of them timeout, but blocks the delivery for a long time
- if one request fails, the following ones are never sent

We should try to see if we can make each request asynchronously, and make handle errors properly to avoid to stop the other tasks.

Plume version (and/or commit): 0.2.0

**Comment by fdb-hiroshima** [comment]
I think the second point was fixed in 4e6f3209, as part of replacing unwrap with error message without panic when no result was required. The first one can probably be implemented easily with reqwest::async, has it as now been stabilized
