### ISSUE TITLE
New visual editor

### ISSUE THREAD

**Issue by BaptisteGelez** [Plume-org/Plume#255]
A new WYSIWYG editor should be added for people who don't know markdown. It should allow you to focus on writing. It will probably need to add some API endpoints for synchronization with the server.

A first version can be found here: https://github.com/Plume-org/Plume/tree/new-editor

And according to this [vote](https://framavox.org/p/SjZHuPWh/what-to-do-with-the-current-editor-), the current editor should be kept.

Plume version (and/or commit): 0.2.0

**Comment by roipoussiere** [comment]
Just a suggestion, but maybe you can create a new tag dedicated to issues voted from Framavox?

In this way we can quickly filter voted issues, adding more transparency to the project, and this will maybe invite some people to join Framavox.

**Comment by BaptisteGelez** [comment]
Good idea, I've added it, along with a "Needs Voting" label for issues that need to be debated first.
