### ISSUE TITLE
Actually federate license

### ISSUE THREAD

**Issue by BaptisteGelez** [Plume-org/Plume#259]
We currently fallback to the default license for remote articles, but it should be federated. I think Peertube federates it, we should see how it is done there.

Plume version (and/or commit): 0.2.0

**Comment by fdb-hiroshima** [comment]
I checked a bit Peertube's code (oh god typescript is better than js), and here are a few thing that we might replicate from them (all of the below vars goes into the `object` part of an activity):
- license is federated via a `licence` tag, which is a 
  ```rust
  struct Licence {
      identifier: String,
      name: String,
  }
  ```
  I assume identifier is an id and name the actual license name, however I haven't time to check yet
- comments are disabled via a `commentsEnabled: bool` (see #270)
- there is an `updated: Date` field, which we might want to use too as we support post update
- icon are federated via a `icon` tag (see #236), which is a 
  ```rust
  struct Icon {
    type: String, //"Image"
    url: String
    mediaType: String, // "image/jpeg"
    width: u32,
    height: u32,
  }
  ```
