### ISSUE TITLE
Article's author is not mentioned in the article itself

### ISSUE THREAD

**Issue by Lucidiot** [Plume-org/Plume#26]
The author is only shown in post lists, not in posts themselves; it could be useful to have their name at the end, at least to remember who wrote it.

**Comment by JosephKiranBabu** [comment]
I will take a stab at implementing this.

**Comment by BaptisteGelez** [comment]
@JosephKiranBabu Great! If you have any question, feel free to ask (here or on the Fediverse, I'm Bat@unixcorn.xyz there).
