### ISSUE TITLE
API docs are not working

### ISSUE THREAD

**Issue by BaptisteGelez** [Plume-org/Plume#263]
[This page](https://plume-org.github.io/Plume/API) is broken.

Plume version (and/or commit): 0.2.0

**Comment by BaptisteGelez** [comment]
A solution may be to generate a static version of this page with ReDoc CLI: https://github.com/Rebilly/ReDoc/blob/master/cli/README.md

**Comment by BaptisteGelez** [comment]
Don't you see the "No layout defined for "StandaloneLayout"" error at the bottom of the page ?

**Comment by fdb-hiroshima** [comment]
I did not until I allowed js

**Comment by BaptisteGelez** [comment]
Fixed in the new repo.
