### ISSUE TITLE
Use the new logo

### ISSUE THREAD

**Issue by BaptisteGelez** [Plume-org/Plume#268]
We now have an official logo:

![plume-feather-trwnh_modifiee](https://user-images.githubusercontent.com/16254623/46584973-5961fd80-ca62-11e8-9ae3-012f524ff6cd.png)

It should be displayed in the header.

The other logos should also be shipped by default, and admins should be able to change the logo of their instance with an environment variable.

[Loomio vote](https://framavox.org/d/R0E91Wd4/plume-s-logo)

Plume version (and/or commit): 0.2.0

**Comment by trwnh** [comment]
for reference, source svg and assets for 1st place and 2nd place: https://github.com/trwnh/plumeLogos

**Comment by BaptisteGelez** [comment]
OK, if we want to make it possible to change the logo with an environment variable, the best solution would be to use switch to Askama, as it would allow us to use `env!()` macros to get the right URL.

I think I will split this issue in two parts, and only add @trwnh's logo until we use Askama.
