### ISSUE TITLE
OpenGraph tags

### ISSUE THREAD

**Issue by BaptisteGelez** [Plume-org/Plume#300]
I tried to integrate [OpenGraph](http://ogp.me/) but it is not working. We should make it work for articles, users and blog pages.

Plume version (and/or commit): 0.2.0

**Comment by BaptisteGelez** [comment]
Looks like they are working actually: https://botsin.space/@readrust/101012063095608355 :woman_shrugging:

**Comment by fdb-hiroshima** [comment]
Hum, I think this was only implemented for articles, not users or blogs
