### ISSUE TITLE
Server error when trying to open editor for an article.

### ISSUE THREAD

**Issue by ognarb** [Plume-org/Plume#314]
Hello,

when opening the editor page to edit an article I get an server error. It only appends when editing an already existing post. Creating a new post work. 

Steep to reproduce:
Create a new post and save it.

Plume version (and/or commit): fediverse.blog / Plume 0.2.0

**Comment by BaptisteGelez** [comment]
Yes, similar issues have already been noticed, but it seems it is only on Fediverse.blog which is very weird…

**Comment by ognarb** [comment]
Ok, maybe an error message with more information is written is the log.

**Comment by BaptisteGelez** [comment]
Yes probably. The problem is that I don't have access to these logs for the moment (I'm not the person hosting fediverse.blog). So I'm really sorry but there is nothing I can do to help yet.

**Comment by ognarb** [comment]
Don't be sorry. I'm aware that plume is not ready for production yet. But it's interesting, I was thinking that you are the administrator of fediverse.blog https://fediverse.blog/about :)

**Comment by BaptisteGelez** [comment]
Yes this page only displays one of the admin/moderator even if we are two to have this status. But the only one who has access to the server is gled.

**Comment by BaptisteGelez** [comment]
I can actually reproduce it on my own instance. Here is the error:

```
Error: Error rendering Tera template 'posts/details'.
Error: Failed to render 'posts/details'
Error: Variable `comment_form` not found in context while rendering 'posts/details'
Error: Template 'posts/details' failed to render.
```

**Comment by fdb-hiroshima** [comment]
Are you sure this is the same error? If it's an error on post edition and assuming the error is in template rendering, shouldn't it be an error on `posts/new`?

**Comment by BaptisteGelez** [comment]
Ah yes you're right, the issue is probably different, I confounded because some people also reported issues on Fediverse.blog when they were trying to read a post while connected…

**Comment by fdb-hiroshima** [comment]
I believe #327 should have fixed this. Feel free to reopen if it did not
