### ISSUE TITLE
Server error when accessing an article

### ISSUE THREAD

**Issue by Turboconnard** [Plume-org/Plume#323]
Hi, i just registered on fediverse.blog, i can see articles if NOT logged, but if i'm logged i can't read anything...

Plume version (and/or commit): fediverse.blog

**Comment by BaptisteGelez** [comment]
This is an error in Tera templates (see https://github.com/Plume-org/Plume/issues/314#issuecomment-440293925). I currently migrating all templates to Ructe, so it should fix the issue.

**Comment by Turboconnard** [comment]
:+1:

**Comment by BaptisteGelez** [comment]
The templates are no longer using Tera. Fediverse.blog is not yet updated, but it will quite soon I think. If you have this issue again in the following days, tell us.
