### ISSUE TITLE
Writing titles in non-ASCII characters causes article URLs being separated with "-"

### ISSUE THREAD

**Issue by ryonakano** [Plume-org/Plume#326]
Generally, Japanese (one of languages that uses non-ASCII characters) does not have any spaces between words, unlike English, French, etc. For example:

**English (has a space between each words):** Writing titles in non-ASCII characters causes article URLs being separated with `-`.
**Japanese (has no space between each words):** 非ASCII文字で記事のタイトルを書くと、URLが`-`で区切られてしまいます。

So separating URLs that includes non-ASCII characters with `-` looks weird (at least in case of Japanese).

## Expected Behavior

The URLs that include non-ASCII characters should not be separated by `-`, e.g: [https://baptiste.gelez.xyz/~/終章/白い悪魔が黒い天国と出会い歴史は紡がれる/](https://baptiste.gelez.xyz/~/%E7%B5%82%E7%AB%A0/%E7%99%BD-%E3%81%84-%E6%82%AA-%E9%AD%94-%E3%81%8C-%E9%BB%92-%E3%81%84-%E5%A4%A9-%E5%9B%BD-%E3%81%A8-%E5%87%BA-%E4%BC%9A-%E3%81%84-%E6%AD%B4-%E5%8F%B2-%E3%81%AF-%E7%B4%A1-%E3%81%8C-%E3%82%8C-%E3%82%8B/)

## Actual Behavior

These URLs are separated by `-`, e.g: [https://baptiste.gelez.xyz/~/終章/白-い-悪-魔-が-黒-い-天-国-と-出-会-い-歴-史-は-紡-が-れ-る/](https://baptiste.gelez.xyz/~/%E7%B5%82%E7%AB%A0/%E7%99%BD-%E3%81%84-%E6%82%AA-%E9%AD%94-%E3%81%8C-%E9%BB%92-%E3%81%84-%E5%A4%A9-%E5%9B%BD-%E3%81%A8-%E5%87%BA-%E4%BC%9A-%E3%81%84-%E6%AD%B4-%E5%8F%B2-%E3%81%AF-%E7%B4%A1-%E3%81%8C-%E3%82%8C-%E3%82%8B/)

Plume version: 0.2.0 (Demo Instance)
(This issue was originally appeared in https://baptiste.gelez.xyz/~/Vaginaplant/titles-have-better-to-be-named-in-ascii-characters/)

**Comment by fdb-hiroshima** [comment]
Thanks for reporting this. This issue come from one of our dependency ([heck](https://github.com/withoutboats/heck)). I'll try to work with them to fix it, however as this code is outside of our direct reach, it might take some time before we get a patch

**Comment by ryonakano** [comment]
Thank you for your quick response. I also confirmed this issue with Chinese title: [https://baptiste.gelez.xyz/~/MyBlog/汉-语-的-标-题](https://baptiste.gelez.xyz/~/MyBlog/%E6%B1%89-%E8%AF%AD-%E7%9A%84-%E6%A0%87-%E9%A2%98/)
