### ISSUE TITLE
any docker images available without build it?

### ISSUE THREAD

**Issue by pwFoo** [Plume-org/Plume#330]
Searched for docker images in docker hub without success.
Is it not possible to build reusable docker images for plume configured by environment?

**Comment by fdb-hiroshima** [comment]
I haven't used Docker much yet, but I'd said it's probably possible to do, through a small script running some `plm` commands on first run.
However as Plume is still in early development stage, I'm not sure such image would be of much use yet. When Plume get production ready, we will most likely provide precompiled binaries as well as a docker image, but Plume is still in alpha, there are no official release for the moment.
There are some instructions [here](https://github.com/Plume-org/Plume/blob/master/docs/INSTALL.md#docker-install) if you want to run Plume in Docker. This is not configured by environment however, but all configuration can be done non interactively via some command options

**Comment by mcrosson** [comment]
https://docker.lollipopcloud.solutions/ has arm32v7 and x86-64 builds available for download via docker pull.

Relevant build script(s): https://git.lollipopcloud.solutions/lollipop-docker/plume

As of 2018/12/10 you need to be using "vfs" or "zfs" docker storage drivers to get a clean build. The above link has builds using "vfs" storage driver so they are a little larger than may be expected (>1Gb on x86-64).

**Comment by BaptisteGelez** [comment]
We now have pre-built docker images (thanks to @mcrosson!), and the process to use them [is documented here](https://docs.joinplu.me/installation/with/docker/).
