### ISSUE TITLE
[bug@ User use is mail on username and create 404

### ISSUE THREAD

**Issue by Dryusdan** [Plume-org/Plume#331]
Hi

A user in my instance set as username his mail..

So, his username is a mail and this mistake create 404 error when I try access on his profile and Plume say this to log: 

```
Dec 01 23:07:07 Arcadia.dryusdan.fr plume[17845]: Error: No matching routes for GET /api/statusnet/config.json application/json.
Dec 01 23:07:07 Arcadia.dryusdan.fr plume[17845]: Warning: Responding with 404 Not Found catcher.
```

Regard

Plume version (and/or commit): 0bb719830a80334515965f5bd0f64aff356a6110 (0.2.0)

**Comment by fdb-hiroshima** [comment]
I don't think there is an `/api/statusnet/config.json` route on Plume, I know this is used by Pleroma, maybe by Mastodon, but not by Plume yet. This url is supposed to contain some metadata about the instance (is registration open...). The part of log you posted don't seems relevant.
However I don't need it to give you an answer. Plume is currently not validating usernames, which leads to some issues, namely difficulties in writing xss countermeasures, and having some user names not accessible by their supposed route (I'm currently working on it). Your case is a bit special, an email is a name@domain so Plume must be trying to fetch it on a remote instance, with no success. Sadly there is not much you can do. You can either modify the database by yourself (which would work but is not exactly a good solution, however if you want to go by that path, I can help you), or ask them to create a new account with the right username (assuming they haven't posted much yet)

**Comment by fdb-hiroshima** [comment]
Do you want any help with modifying the database? It will require some SQL and Plume model knowledge (or did I misunderstood your answer?)

**Comment by fdb-hiroshima** [comment]
I think you forgot `ap_url='https://catlife.drycat.fr/@/Lou_H/'`, but else you're good

**Comment by fdb-hiroshima** [comment]
I've made so it won't happen again in 9714bafded2aefeaf2eb4123a338b93c4cd019d8. May I close the issue?

**Comment by Dryusdan** [comment]
Yeah, thank your for your help :)

And thank for this commit, is cool o/

Thank and nice day :)
