### ISSUE TITLE
Can't follow plume user from mastodon

### ISSUE THREAD

**Issue by fdb-hiroshima** [Plume-org/Plume#334]
It seems like federation with mastodon might be broken again, at least when receiving follow activities

Plume version (and/or commit): 0.2.0

**Comment by ffffluffy** [comment]
I've currently issues also for boosts, likes and comments (for instance, this : https://eldritch.cafe/@fluffy/101213334358198658)

**Comment by fdb-hiroshima** [comment]
It's strange, all three (boosts like and comment) worked for me on [an other instance](https://fediverse.blog/~/PlumeDev/adding-full-text-search-to-plume), but I can see your answer not getting fevered to baptiste.gelez.xyz , and I can reproduce from my own Mastodon account to your post. @BaptisteGelez there seems to be an issue with federation specific to your instance

**Comment by BaptisteGelez** [comment]
I'm getting this error when trying to like/boost your post from Mastodon:

```
Rejected invalid activity supposedly from Bat, with headers
HeaderMap {
  headers: {
    Uncased { string: "Host" }: ["localhost:3033"],
    Uncased { string: "User-Agent" }: ["http.rb/3.3.0 (Mastodon/2.6.1+glitch; +https://social.wxcafe.net/)"],
    Uncased { string: "Connection" }: ["close"],
    Uncased { string: "Content-Length" }: ["1342"],
    Uncased { string: "Accept-Encoding" }: ["gzip"],
    Uncased { string: "Content-Type" }: ["application/activity+json"],
    Uncased { string: "Date" }: ["Mon, 10 Dec 2018 11:54:15 GMT"],
    Uncased { string: "Digest" }: ["SHA256=eObO1TC6CsLd1vC1MeSN4ap2sRriQJCaDnu7P4oabfo="],
Uncased { string: "Signature" }: ["keyId=\"https://social.wxcafe.net/users/Bat#main-key\",algorithm
=\"rsa-sha256\",headers=\"(request-target) host date digest content-type\",signature=\"P3KWEEWPZ+cFruZaY4jqU4ntHrOI+KNUnASFFkq1mGpKVc9fZu1zsGUPKawL6b441wLQvQ0mNBJolo9TK8Xfk6LU6EGca/e3T
qnqnGYHMgC7y/0zON5UaKAEYmrOQ8nQKlZAppmuqcNEOO2Wqm8cpAbhKw7rZIr7Ug4T0QmH/1zl2HFBUwtD3GnH4RmOsWERvmWpTuYBzcJIJ2MScRBBBYCeliKZKB75iDXmotUtVqL2KnosZ7TsrNuc+Ugl0vanwUnBu01RYBnf+GPIQZxR3UX/V
W10WFmzuHOp2hijm5s3vOL97/r0FegWAhYtN0/ay7dBN3nCec2OiM+aIU6kqg==\""],
    Uncased { string: "X-Forwarded-For" }: ["188.40.106.245"],
    Uncased { string: "(request-target)" }: ["post /@/fluffy/inbox"]
  }
}
```

**Comment by fdb-hiroshima** [comment]
What is the full date on your server?

**Comment by BaptisteGelez** [comment]
`date` gives me `Mon Dec 10 12:13:20 UTC 2018`

**Comment by fdb-hiroshima** [comment]
It's well inside the 11:54 ± 12h range. Could you log what enum variant `verify_http_headers()` is returning, and maybe add some debug prints in it's body?

**Comment by BaptisteGelez** [comment]
I'll do it this evening and tell you what I got. :slightly_smiling_face:

**Comment by BaptisteGelez** [comment]
It returns from here: https://github.com/Plume-org/Plume/blob/master/plume-common/src/activity_pub/sign.rs#L171

If you need any other info, tell me.

**Comment by fdb-hiroshima** [comment]
I think I got it, your reverse proxy is modifying Host to `localhost:3033` where it should leave it unchanged for signature to match

**Comment by BaptisteGelez** [comment]
Indeed, I fixed my reverse proxy config, and it seems to work again.

**Comment by fdb-hiroshima** [comment]
Can we close this issue?

**Comment by fdb-hiroshima** [comment]
There is still something going on in general. Plume list new followers as expected on `/@/<name>/followers`, but don't emit notification in `/notifications`. On Mastodon the follow status seems to indicate it did not receive the follow confirmation (Accept activity).
It also don't add new posts to the timeline, however this might be because Mastodon consider Masto-user don't follow Plume-user yet.
Mentions are also ignored by Mastodon (as mentioned in #172)
