### ISSUE TITLE
tantivy fails to compile

### ISSUE THREAD

**Issue by gled-rs** [Plume-org/Plume#337]
Plume version (and/or commit): d6e220cc8dbe0c21a563e080cc4023241669fc84

rustc --version: rustc 1.29.0-nightly (1ecf6929d 2018-07-16)

cargo install --force --verbose:
[out.log](https://github.com/Plume-org/Plume/files/2645738/out.log)

cat /etc/debian_version: 9.6

Let me know if you need more informations... maybe I missed something ?!

**Comment by BaptisteGelez** [comment]
First of all, you should probably update your Rust installation to the version specified in the `rust-toolchain` file (normally Rustup does it for you, but it looks like it is not the case). Then try to re-compile. If it still doesn't work, try to `cargo clean` and to build once again. I had some issues the first I tried to compile tantivy too (and another person is having issue as well), but re-trying magically fixed the problem…

**Comment by fdb-hiroshima** [comment]
It's very strange, I did try in a fresh new debian 9.6 vm and it built just fine. This is not rust-toolchain being ignored, nightly-2018-07-16 can't compile our version of proc-macro2 so another issue would have appeared earlier.
`cargo clean` might help, but I'd still like to know what make sigsegv rustc, this is a pretty serious issue. It seems this might be a similar issue to rust-lang/rust#55068 (which seems to only concern armv7 target)

**Comment by maximesrd** [comment]
I've got the same issue,  and I've found a solution. 

You have to force postgres to remake a cargo build after cargo clean 
cargo build --features postgres 

After,  you can do cargo install --force --verbose --features postgres and finally cargo run

**Comment by gled-rs** [comment]
$ uname -a:
Linux plumehost 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux

$ rustup show
Default host: x86_64-unknown-linux-gnu

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-2018-05-31-x86_64-unknown-linux-gnu
nightly-2018-07-17-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

active toolchain
----------------

nightly-2018-07-17-x86_64-unknown-linux-gnu (overridden by '/home/plumeuser/Plume/rust-toolchain')
rustc 1.29.0-nightly (1ecf6929d 2018-07-16)

$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

$ cargo clean && cargo install --force:
 same issue ( tried twice ).

$ cargo clean && cargo build --release --features postgres && cargo install --force --features postgres: 
same issue ( tried twice again ).

$ cargo clean && cargo build --features postgres && cargo install --force --features postgres: fails at the cargo install steps.

$ cargo clean && cargo build --features postgres && cargo install --debug --force --features postgres: woohooo finally !

**Comment by BaptisteGelez** [comment]
The `ructe` branch has been merged, so I think we can close this issue. If anyone has the problem again, tell us, we will re-open and try to find what is wrong.

**Comment by mcrosson** [comment]
I managed to get this built with docker on a xeon machine with zfs as the docker filesystem driver using a tweaked version of the above.

Full docker file for those who are wondering what they may need to do with docker:

```
FROM rust:1-stretch

RUN apt-get update && apt-get install -y --no-install-recommends \
    gettext \
    postgresql-client \
    libpq-dev \
    git \
    curl \
    gcc \
    make \
    openssl \
    libssl-dev
WORKDIR /app
COPY Cargo.toml Cargo.lock ./
RUN cargo install diesel_cli --no-default-features --features postgres --version '=1.3.0'
COPY . .
RUN cargo clean
RUN cargo build --no-default-features --features postgres
RUN cargo install --debug --force --no-default-features --features postgres
RUN cargo install --debug --force --path plume-cli --no-default-features --features postgres
RUN rm -rf target/debug/incremental
CMD ["plume"]
EXPOSE 7878
```
