### ISSUE TITLE
Unable to open Plume article if logged

### ISSUE THREAD

**Issue by ffffluffy** [Plume-org/Plume#345]
I'm currently unable to read Plume article while logged (on baptiste.gelez.xyz) It may be related to #323. I'm currently unable to edit drafts as well. When I click on a link, such as https://baptiste.gelez.xyz/~/Contribu%C3%ADndoAoFediverso@fediverse.blog/visitando-o-mosteiro-de-caaveiro-a-capela/ for instance, I just stay on the same page, or sometimes I get a server error (the two can happen on the same link, the server error is more rare though.

Plume version (and/or commit): 0.2.0

**Comment by BaptisteGelez** [comment]
Yes, this instance have not been updated since this issue was fixed. I will update it right now.

**Comment by BaptisteGelez** [comment]
Fixed!
