### ISSUE TITLE
H-feed doesn't find articles for user

### ISSUE THREAD

**Issue by swentel** [Plume-org/Plume#350]
So this is not related with https://github.com/Plume-org/Plume/pull/347 - I thought it would fix the feed, but that space isn't the problem afaics, because parsing the feed for the local or full network is fine, that's great!

See
- http://xray.p3k.io/parse?url=https%3A%2F%2Fbaptiste.gelez.xyz%2Flocal&pretty=true
- http://xray.p3k.io/parse?url=https%3A%2F%2Fbaptiste.gelez.xyz%2Ffederated&pretty=true

However, the list for an author only finds the h-card, even though microformats are available there.
See http://xray.p3k.io/parse?url=https%3A%2F%2Fbaptiste.gelez.xyz%2F%40%2F0x1C3B00DA&pretty=true

It's going to be something subtle, will look at this when I have more time to investigate this week!

**Comment by fdb-hiroshima** [comment]
Actually looking at the html I get from `curl https://baptiste.gelez.xyz/@/0x1C3B00DA | grep 'url"href'`, I'd say baptiste.gelez.xyz is just not up to date. I'll bring back online my test instance in the afternoon to check if it's ok with master

**Comment by swentel** [comment]
That's true, however, on local, the space problem is still there too, but that one parses fine, so something else is at play, debugging a bit as I type this :)

**Comment by fdb-hiroshima** [comment]
I've tested on current master and there is still an issue, no feed is found for user pages

**Comment by swentel** [comment]
Mm well, that's because xray does more things than just parsing mf2. For some reasons it thinks that page is an activity stream. So might rather be something within the xray project. I'll investigate that a bit.

**Comment by zcdunn** [comment]
Unfortunately, I can't reach baptiste.gelez.xyz right now. I'll try again in a bit

**Comment by zcdunn** [comment]
I was able to subscribe to my user feed and my test post showed up in my reader

**Comment by fdb-hiroshima** [comment]
So shall we consider this is a Plume issue or an xray one? I searched for unbalanced tags in our templates, or things like that. I can't find anything making `/@/<user>` truly different from just `/`. The issue also appear on `/~/<blog>`, and again I have no idea why

**Comment by swentel** [comment]
So I'm using http://php.microformats.io/ now.
It finds the the articles for the first feed on https://baptiste.gelez.xyz/@/0x1C3B00DA so that's fine

The reason xray (on xray.p3k.io) doesn't find them by default is because it accepts application/activity+json

<code>curl --header "Accept: application/activity+json" https://baptiste.gelez.xyz/@/0x1C3B00DA</code>

So as far as microformats, everything is fine and I think closing is fine :)

**Comment by fdb-hiroshima** [comment]
We won't change how Plume react to application/activity+json as it is required to federate via ActivityPub, which is our primary goal.
If someone find a way to make Plume and xray communicate without breaking AP federation I'm all ears, in the mean time I'll close this issue
