### ISSUE TITLE
Allow customised blogs at user-level

### ISSUE THREAD

**Issue by puffinux** [Plume-org/Plume#354]
A page or area where you can customise the way blog posts look for your (the user) posts only would be appreciated. A simple GUI and also (or alternatively) a custom CSS text area. This could enhance blogs and would be a great feature to add. WriteFreely are doing it successfully.

**Comment by BaptisteGelez** [comment]
This would indeed be great. I think a simple GUI allowing to change only a few elements would be better, since allowing any CSS could result in privacy issues (loading remote images for analytics for instance).

**Comment by fdb-hiroshima** [comment]
I think all urls in css must be inside of `url(...)`, so we might allow nearly any css if we sanitize this special tag
