### ISSUE TITLE
Redirect to login instead of showing 404 page

### ISSUE THREAD

**Issue by BaptisteGelez** [Plume-org/Plume#37]
When a page is not available because the user is not logged in, Rocket sends a 404 page. We should instead redirect to the login page with an explanation.

**Comment by fdb-hiroshima** [comment]
more or less related : going to /logout without being connected generate a 500

**Comment by BaptisteGelez** [comment]
I guess this have been close by #45 (tell me if it's not the case).

**Comment by fdb-hiroshima** [comment]
whoops, looks like I forgot to look at `src/routes/user.rs`, there are three routes still returning 404 here. I'll push something today or tomorrow to fix that
