### ISSUE TITLE
Invalid email during registration - a very rare problem?

### ISSUE THREAD

**Issue by marek-lach** [Plume-org/Plume#385]
This is extremely hard to reproduce, and I've tried, but failed to encounter this problem myself. I have only ever seen one person mention the issue on Mastodon, but... Still, it may be worth looking into how email format is checked during registration in Plume, and I am posting it here just in case it tells you something @BaptisteGelez, or @fdb-hiroshima.

So, the problem that https://sunbeam.city/@alyxmaia seems to have is that when they try to register on a plume instance such as fediverse.blog, or cafe.sunbeam.city, they encounter an 'invalid email' error during the registration process, even when the email address seems to be perfectly fine.

![plume__invalid_email](https://user-images.githubusercontent.com/45913977/50424321-c31bc780-0859-11e9-87fe-5b254ceaad04.png)

I find this odd, because I have tried registering an account on these instances with an email address that did not exist, and the account was succesfully created without any problems, since Plume does not send confirmation emails.

Trying to find out more about this issue, I understand that they were using the built-in Chromium layer integrated as part of the Mastlab Mastodon client on Android. To reproduce this scenario, I installed Mastlab on Android, clicked through it on the link within this toot https://mastodon.xyz/@mareklach/101302155852725410, to be able to go through to cafe.sunbeam.city via the Mastlab built-in browser, but was successful registering an account, and so unable to reproduce the invalid email problem.

I have told them to disable all ad-blocking apps, but apparently it didn't help. Even in a desktop chrome browser they've apparently got the same issue.

Plume version (and/or commit): master from 2 days ago, but also older version on fediverse.blog

**Comment by BaptisteGelez** [comment]
I can reproduce if I add a space after the email address, I think this is the issue, since keyboards on Android tend to do this sometimes.

**Comment by marek-lach** [comment]
I thought it was something as easy, can I modify the invalid email message to include also ...''make sure not to leave any blank spaces before, or after'  ?

**Comment by fdb-hiroshima** [comment]
I think we should just trim white-spaces before validating&saving

**Comment by marek-lach** [comment]
Right. That seems ideal 👍
