### ISSUE TITLE
Create a multi step docker image

### ISSUE THREAD

**Issue by dfeyer** [Plume-org/Plume#411]
Currently the docker image is huge, and I want to work on a multi step build image. I don't have too much experience with rust, so I need you help to make this happens ;)

A >1Go image size is a bit insane, and it does not make sense to have git and all the build tools for the production image. 

A basic multi step build Dockerfile:

```
FROM rust:1-stretch as builder

RUN apt-get update && apt-get install -y --no-install-recommends \
    gettext \
    postgresql-client \
    libpq-dev \
    git \
    curl \
    gcc \
    make \
    openssl \
    libssl-dev

WORKDIR /scratch
COPY Plume/script/wasm-deps.sh .
RUN chmod a+x ./wasm-deps.sh && sleep 1 && ./wasm-deps.sh

WORKDIR /app
COPY Plume/Cargo.toml Plume/Cargo.lock Plume/rust-toolchain ./
RUN cargo install diesel_cli --no-default-features --features postgres --version '=1.3.0'
RUN cargo install cargo-web

COPY Plume/. .

RUN chmod a+x ./script/plume-front.sh && sleep 1 && ./script/plume-front.sh
RUN cargo install --path ./ --force --no-default-features --features postgres
RUN cargo install --path plume-cli --force --no-default-features --features postgres
RUN cargo clean

FROM debian:stretch-slim

WORKDIR /app

COPY --from=builder /app /app
COPY --from=builder /usr/local/cargo/bin/diesel /bin/

CMD ["plume"]

EXPOSE 7878
```

Is it enough to just copy /app and diesel from the builder image ?

**Comment by igalic** [comment]
from your build instructions, i think i would also build the same thing for sqlite

**Comment by dfeyer** [comment]
A bit more complex than expected ;) and my rust knowledge doesn't help 

The build works, but diesel is linked to pgsql lib, so not fully staticaly build.

I try to use the ekidd/rust-musl-builder:nightly docker image as buidler, but end up with some errors during diesel install step:

```
  Downloaded version_check v0.1.5
  Downloaded cc v1.0.28
  Downloaded semver v0.9.0
  Downloaded semver-parser v0.7.0
   Compiling semver-parser v0.7.0
   Compiling proc-macro2 v0.4.24
   Compiling cc v1.0.28
   Compiling libc v0.2.46
   Compiling version_check v0.1.5
   Compiling unicode-xid v0.1.0
   Compiling autocfg v0.1.1
   Compiling unicode-xid v0.0.4
   Compiling pq-sys v0.4.6
   Compiling cfg-if v0.1.6
error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-unknown-linux-musl` target may not be installed

error: aborting due to previous error
```

But when I list the available target, look like x86_64-unknown-linux-musl is installed ...

**Comment by dfeyer** [comment]
I took the "easiest" way, install the missing libraries currently, the image size if 266Mo not that bad, currently testing to see if everthing works, diesel is working correctly now.

**Comment by dfeyer** [comment]
If we need slimer image, we have to go with a musl based build and used an alpine based image, or even scratch, we should have something working with an image weight around 60-80Mo, but the current 130Mo is good compared to the >1Go with single step build. 

I can prepare a PR to use this as the default build and to make it easier for testing tomorrow

**Comment by thibaultamartin** [comment]
Hey thanks @dfeyer for your work here.

I see from the [documentation](https://docs.joinplu.me/installation/with/docker) that some commands need to be run at first launch.

Wouldn't it be a best practice to have those commands in the entry point of plume's image (checking if a database/table exists, and if not creating it)? If any user input is required (i.e. if the init is interactive), wouldn't it be better to use environment variables?
