### ISSUE TITLE
Use Rust 2018

### ISSUE THREAD

**Issue by AnaGelez** [Plume-org/Plume#423]

**Comment by igalic** [comment]
does that mean we finally go stable?

**Comment by BaptisteGelez** [comment]
No, editions are just the way Rust deals with breaking changes in the language (for instance, the module system now have a slightly different syntax with Rust 2018, that would not work in the 2015 edition). So we will still have to use Nightly version until all features Rocket needs are stabilized.

**Comment by igalic** [comment]
now that so many PRs are closed, we can try this again
