### ISSUE TITLE
Syntaxic coloration

### ISSUE THREAD

**Issue by AnaGelez** [Plume-org/Plume#424]
We could use [`syntect`](https://crates.io/crates/syntect) to make code blocks nicer.

Plume version (and/or commit): 0.2.0

**Comment by ksteimel** [comment]
[This issue](https://github.com/raphlinus/pulldown-cmark/issues/167) has good information about how to add this functionality. I may try to implement this once I feel more confident in rust.

**Comment by BaptisteGelez** [comment]
Our custom markdown transformations (parsing mentions and hashtags mainly) currently live here: https://github.com/Plume-org/Plume/blob/master/plume-common/src/utils.rs#L44

(this function is quite horrible, and would probably need to be cleaned up)

If you want me to mentor you on this, just ask. I think it can be a good occasion to discover Rust (I don't know how much you already used it).

**Comment by igalic** [comment]
would syntect work thru wasm? for (live?) previews in the (new) editor?

**Comment by BaptisteGelez** [comment]
It depends on `walkdir`, which requires a file system to work, so I don't think so. However, I think its maintainers would be happy if we made this dependency optional (I don't think it is vital), so maybe we could get in touch with them and propose a PR.

**Comment by fdb-hiroshima** [comment]
I've tried, it seems to be just a matter of adding a dozen of `#[cfg(feature = "something")]` at the right place to make it compile with cargo web

**Comment by AnaGelez** [comment]
Can probably be closed.
