### ISSUE TITLE
"422: Unprocessable Entity" - inssuficient error message

### ISSUE THREAD

**Issue by Granitosaurus** [Plume-org/Plume#425]
I'm trying to test some markdown. Primarily I used [this document](http://daringfireball.net/projects/markdown/syntax.text)
from https://stackoverflow.com/questions/2238012/

However upon pressing submit I'm redirected to 422 error message that doesn't really give any real information:

> 422: Unprocessable Entity
> The request was well-formed but was unable to be followed due to semantic errors.

I've deleted around the page source and something is breaking the post; would be nice if the error message could say what is breaking the submission.  

Same with commonmark's spec file: https://raw.githubusercontent.com/commonmark/CommonMark/master/spec.txt

Plume version (and/or commit): 0.2.0

**Comment by BaptisteGelez** [comment]
I think we can use this configuration option: https://rocket.rs/v0.4/guide/configuration/#data-limits

**Comment by Granitosaurus** [comment]
Interesting, would it possible to wrap the error up somehow? Right now it's very difficult to debug.

**Comment by fdb-hiroshima** [comment]
probably, by creating an error handler for error 422

**Comment by igalic** [comment]
> I think we can use this configuration option: https://rocket.rs/v0.4/guide/configuration/#data-limits

it would be cool to expose this config option in the `.env`, and show the (remaining | max) characters characters in the Post UI

i think for now, .env is enough, and we should be able to handle a (graceful) restart to reload the config
