### ISSUE TITLE
Nodeinfo improvements and fix

### ISSUE THREAD

**Issue by rhaamo** [Plume-org/Plume#433]
Plume version (and/or commit): latest

Fix:
- Nodeinfo `software.name` should be lowercase
- `openRegistrations` seems to always be true even if deactivated

Improvements:
Add some metadata:
- `nodeName`: instance name
- `nodeDescription`: instance short description

**Comment by zcdunn** [comment]
`software.repository` was [recently added](https://github.com/jhass/nodeinfo/issues/31 "Nodeinfo issue adding repository key") to nodeinfo. Could that also be added? The key was added in a new schema version(2.1), so that might be an issue.

**Comment by rhaamo** [comment]
Side note, if implementing `software.repository`, make it configurable (.env) to point to a fork if needed.
