### ISSUE TITLE
Medias: uploaded image with uppercase extension don't work

### ISSUE THREAD

**Issue by rhaamo** [Plume-org/Plume#436]
If uploading a picture with uppercase extension like `foobar.JPG`, the upload works but the resulting page don't have picture or markdown thingy.
![image](https://user-images.githubusercontent.com/8625/51679522-7275c680-1fdf-11e9-94ee-ed477a5d0233.png)

If I rename `JPG` to `jpg`, everything works fine.

I don't see an error in logs, and debug is way to verbose to understand anything.

Plume version (and/or commit): latest

**Comment by BaptisteGelez** [comment]
It is because the code to detect the type of the media (and generate its preview and markdown code) is based on the file extension, and only matches lowercase extensions for the moment. The fix would probably be to lowercase the extension before matching.
