### ISSUE TITLE
Blog icon/avatar and banner

### ISSUE THREAD

**Issue by BaptisteGelez** [Plume-org/Plume#454]
We should be able to select a blog avatar/icon and a banner for a blog. However this would probably require adding another file upload endpoint in the blog settings, and I don't think it is a good idea until there is support for file upload directly in Rocket, as the code we currently have to handle that is quite big and may be hard to make more generic.

Plume version (and/or commit): 0.2.0

**Comment by igalic** [comment]
why not just use the media upload?

**Comment by BaptisteGelez** [comment]
Ah, yes we could have a list like for the article cover.
