### ISSUE TITLE
Delete notification when deleting comment

### ISSUE THREAD

**Issue by BaptisteGelez** [Plume-org/Plume#463]
We don't delete the notification associated with a comment when deleting this comment, which can break the notification page if a comment gets deleted.

Plume version (and/or commit): 0.2.0

**Comment by vbrandl** [comment]
I'm thinking of tackling this issue but I don't know the code base yet. I would try it like this:

Implement `find_by_comment` for `Notification`, then loop over the results and delete them one by one, like here: https://github.com/Plume-org/Plume/blob/master/plume-models/src/comments.rs#L333

**Comment by fdb-hiroshima** [comment]
That looks like a good solution, just make sure to filter by notification kind as the object_id field of Notification can also be a reference to other things than comments. If you need any help, feel free to ask on Matrix at #plume:disroot.org , or here :wink:
