### ISSUE TITLE
/configure public accessible

### ISSUE THREAD

**Issue by MoritzFago** [Plume-org/Plume#47]
[/configure](http://baptiste.gelez.xyz/configure) is currently publicly accessible. This could be a security issue.

**Comment by BaptisteGelez** [comment]
We should probably rethink the instance setup anyway. What I'm thinking about is to have a `plume` command which asks you questions to setup the instance (like instance name, domain, but also DB URL) and create the admin account, setups the instance, and then launches it (and just launches if it have been configured). It would mean installing Plume would just be `cargo install plume` (and most of the time setting up a service and a reverse-proxy).
