### ISSUE TITLE
Potential security risk: uploaded pictures accessible

### ISSUE THREAD

**Issue by MrSoUndso** [Plume-org/Plume#475]
While being logged in with any account, the user is able to view all pictures uploaded to the website. To reproduce: go to https://fediverse.blog/medias/4620 for example. Just by knowing the 4-digit id of a picture, everybody can see a picture uploaded by any account, no matter if the author decided to publish it or not. A malicious actor could brute-force/guess all ids, granting him access to all pictures on the instance. They would also be able to delete the picture.

Please fix this as fast as possible!

- **Plume version:** 0.2.0

**Comment by fdb-hiroshima** [comment]
This should have been fixed in #410. @BaptisteGelez is fediverse.blog up to date?

**Comment by BaptisteGelez** [comment]
Huuuhh… not very much I think. I will update now.
