### ISSUE TITLE
Tests: add "redo" operation to migrations

### ISSUE THREAD

**Issue by igalic** [Plume-org/Plume#488]
When adding migrations, it's good to test them with `diesel migration redo`
Since we do our migrations entirely in code, we should also add *that* to our test code.

To achieve this, after a successful `run`, we have to `revert`, and then `run` again.

**Comment by fdb-hiroshima** [comment]
Fixed by #513 
https://github.com/Plume-org/Plume/blob/master/script/run_browser_test.sh#L11
