### ISSUE TITLE
clicking 'publish' on a new post leaves the post as draft at 732f514

### ISSUE THREAD

**Issue by khimaros** [Plume-org/Plume#495]
1) create a new blog
2) create a new post and click "publish"
3) note that the state of the post is still "draft"

- **Plume version:** commit 732f514
- **Operating system:** Debian 10
- **Web Browser:** Chromium

**Comment by BaptisteGelez** [comment]
This bug is normally fixed in #486

**Comment by fdb-hiroshima** [comment]
Closing as #486 got merged, feel free to reopen if the issue is still here
