### ISSUE TITLE
Mobile feed view is too narrow

### ISSUE THREAD

**Issue by Granitosaurus** [Plume-org/Plume#504]
Feed views on mobile are very narrow which makes for a very difficult browsing. The "latest articles" is the only one not affected by this.

Tested on plume.mastodon.host instance. 

![Narrow](https://i.imgur.com/p3J5dwK.jpg)

**Comment by BaptisteGelez** [comment]
Hello. Do you have any idea what your screen resolution is? And I guess it was on plume.mastodon.**host**, right? Thank you. :slightly_smiling_face:

**Comment by Granitosaurus** [comment]
My phone says 2240 x 1080
Comparison screenshot:
![narrow](https://i.imgur.com/IcAo8Ky.jpg)

**Comment by marek-lach** [comment]
The view shrinks whenever you click on either 'Federated feed', or 'Local feed' on fediverse.blog

As per testing, this issue is **NOT present** on the _cafe.sunbeam.city_ instance.

**Comment by BaptisteGelez** [comment]
I think there is a CSS class that is applied on the article lists on the homepage, but not on the other page, and that is causing this bug.
