### ISSUE TITLE
Show previous comment when commenting

### ISSUE THREAD

**Issue by BaptisteGelez** [Plume-org/Plume#51]
When responding to a comment, we should display this comment above the text entry.

**Comment by Madeorsk** [comment]
I think it could be better to comment directly on the article page instead of redirecting on another void page for edition. This would also solve this issue at the same time, as the text entry could be displayed under the comment so you can still see what you are responding to.

**Comment by BaptisteGelez** [comment]
Fixed in 461c26f1594e3ef6b75ad66d67a45f82d3dc2d77 and 4c211b4308d718e468ed6b3444f5a152400b746b

It would need a better design tho, I don't really like what we have…
