### ISSUE TITLE
ci is caching too much artifact

### ISSUE THREAD

**Issue by fdb-hiroshima** [Plume-org/Plume#523]
The continuous integration is configured to cache to much build artifact. In [this build](https://circleci.com/gh/Plume-org/Plume/831) you can see it causes some tests to be run 2 or 3 times

**Comment by BaptisteGelez** [comment]
Maybe just running `rm target/debug/plume-*` would be enough?

**Comment by fdb-hiroshima** [comment]
I think it will be the easiest fix as I did not find ways to exclude certain files, but there is more than just `plume`, there is also `plume_models`, `lib`, ...
