### ISSUE TITLE
Preprocessor directives considered hashtags

### ISSUE THREAD

**Issue by bugaevc** [Plume-org/Plume#534]
With the new 0.3 release (congrats! :tada:) supporting hashtags in post body, Plume now considers C-style preprocessor directives (like `#include`) in code blocks to be hashtags.

Example: https://fediverse.blog/~/3542/understanding-rust-ownership-borrowing-lifetimes

**Comment by KitaitiMakoto** [comment]
@bugaevc This should be fixed in the current version. Can you check it by re-saving the post?

**Comment by bugaevc** [comment]
Yep, thanks, that fixed it! 😀

There even appears to be some syntax highlighting now.

**Comment by KitaitiMakoto** [comment]
Yay!
