### ISSUE TITLE
plume 0.3.0 (Alpha 2) postgresql and sql builds .tar.gz seem broken

### ISSUE THREAD

**Issue by yalh76** [Plume-org/Plume#538]
After downloading https://github.com/Plume-org/Plume/releases/download/0.3.0-alpha-2/plume-postgres.tar.gz and https://github.com/Plume-org/Plume/releases/download/0.3.0-alpha-2/plume-sqlite.tar.gz. the *.tar.gz can't be opened or extracted

Error:
```bash
$ wget https://github.com/Plume-org/Plume/releases/download/0.3.0-alpha-2/plume-postgres.tar.gz
$ tar -xvzf plume-postgres.tar.gz
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

- **Plume version:** 0.3.0 (Alpha 2)
- **Operating system:** Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux
Also tested on windows 10
- **Web Browser:** None

**Comment by BaptisteGelez** [comment]
For some reason, they are compressed twice. Until we find a better solution, you can extract them with:

```
gzip -dc plume-postgres.tar.gz | tar -xvzf -
```

**Comment by fdb-hiroshima** [comment]
This is now fixed
