### ISSUE TITLE
Support hashtags

### ISSUE THREAD

**Issue by BaptisteGelez** [Plume-org/Plume#54]
I'm thinking about hashtags in text, not tags for articles.

**Comment by zcdunn** [comment]
What would be the difference between hashtags in text and article tags? Or are they meant to be two different ways to do the same thing?

**Comment by BaptisteGelez** [comment]
They would be quite similar, I think. Actually, hashtags would mainly be here for interoperability with other Fediverse softwares (for instance, if you receive a comment from Mastodon or Pleroma containing a hashtag, Plume should understand it is a hashtag). Regular tags would also have a dedicated space at the end of the article to be displayed. But both could be searched for the same way, and I think we will have a page listing articles containing a specific tag (both regular ones, and hashtags).
