### ISSUE TITLE
Cargo.toml missing in pre-compiled builds

### ISSUE THREAD

**Issue by yalh76** [Plume-org/Plume#543]
Going threw the steps https://docs.joinplu.me/installation/with/prebuilt and https://docs.joinplu.me/installation/config using https://github.com/Plume-org/Plume/releases/download/0.3.0-alpha-2/plume-postgres.tar.gz

When executing `diesel migration run` there is an error:
https://paste.yunohost.org/gimawuzuri.rb

When putting https://github.com/Plume-org/Plume/blob/master/Cargo.toml in the directory, installation continues and works

- **Plume version:**  0.3.0 (alpha 2)
- **Operating system:** Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux
- **Web Browser:** none

**Comment by AnaGelez** [comment]
I think this issue can be closed, as we don't use `diesel` anymore.
