### ISSUE TITLE
Date and time displayed for when comments are posted

### ISSUE THREAD

**Issue by marek-lach** [Plume-org/Plume#544]
**Is your feature request related to a problem? Please describe.**
Currently, when there's a comment on a post, there's no date and time shown of when that comment was posted.

<img width="775" alt="Screenshot 2019-04-24 at 08 54 28" src="https://user-images.githubusercontent.com/45913977/56655192-64911980-6692-11e9-8b0f-2ec18832b4a5.png">

**Describe the solution you'd like**
In a similar vein how the date of a post is displayed, the date of a comment (and maybe the time in hours:minutes format too) should be displayed next to every comment. This would help both authors and readers to figure out which comments are relatively new, which are quite old and so on...

**Describe alternatives you've considered**
None

**Additional context**
For illustrative purposes, in WP the date/time in comments are displayed like this:
<img width="744" alt="Screenshot 2019-04-24 at 15 02 55" src="https://user-images.githubusercontent.com/45913977/56661526-31ef1d00-66a2-11e9-96ed-204eebd3552b.png">

For Plume, I think having the date and time displayed at the far right side of a commment, at the same level as the username, would look nice...

**Comment by igalic** [comment]
> For Plume, I think having the date and time displayed at the far right side of a commment, at the same level as the username, would look nice...

given how long usernames on the fediverse can get, perhaps we should stick with the WordPress style

**Comment by marek-lach** [comment]
> given how long usernames on the fediverse can get, perhaps we should stick with the WordPress style

Hm... that's a rather fair point that didn't occur to me :-)

**Comment by marek-lach** [comment]
Closed by #553
