### ISSUE TITLE
Invalid path for Crowdin files

### ISSUE THREAD

**Issue by BaptisteGelez** [Plume-org/Plume#569]
For some reasons the files we upload on crowdin are no longer in the correct directories, and are thus duplicated, for example here : https://crowdin.com/project/plume/fr

The config file seems correct, so I don't really know where does the issue comes from…

**Comment by marek-lach** [comment]
Possibly linked to the Crowdin interactions automization process of #558?

**Comment by BaptisteGelez** [comment]
Yes probably.
