### ISSUE TITLE
Arch Linux Packaging Question

### ISSUE THREAD

**Issue by sequencer** [Plume-org/Plume#579]
I'm tying to package plume into Arch Linux with files show below
```
./etc/plume/config
./usr/share/licenses/plume/LICENSE
./usr/lib/systemd/system/plume.service
./usr/lib/sysusers.d/plume.conf
./usr/lib/plume/
./usr/bin/plume
./usr/bin/plm
```
Here is the systemd file:
```
[Unit]
Description=plume

[Service]
Type=simple
User=plume
ExecStart=/usr/bin/plume
EnvironmentFile=/etc/plume/config
WorkingDirectory=/usr/lib/plume
TimeoutSec=30
Restart=always

[Install]
WantedBy=multi-user.target
```
And here are some of my questions:
1. Is it possible to build a plume with 2 database backend including `pg` and `sqlite`, I found with enable all features, `plume-cli` will refuse to compile  
2. What should be packaged into a working dir in `/usr/lib/plume`? After I run plume with systemd, I failed to run database migration with `Unable to find migrations directory in this directory or any parent directories.

- **Plume version:** 0.3.0-alpha-2
- **Operating system:** Arch Linux
- **Web Browser:** Firefox
Here is the [pkgbuild](https://github.com/sequencer/pkgbuild_plume)

**Comment by BaptisteGelez** [comment]
Hello! Nice to see you are working on an Arch Linux package!

To answer your questions:

1. No, it is not possible, and would probably be very hard to do technically (we tried once, but were quickly limited by Rust and our ORM)
2. I think you should package the `migrations/DATABASE` directory (where `DATABASE` is `postgres` or `sqlite`), and `static`. Also, you should have a `.env` file in this directory, but you can probably link it from `/etc/plume/config`.

**Comment by sequencer** [comment]
After
```
diesel migration run
plm instance new
plm users new --admin
```
when I tried to run
```
plm search init
```
failed with
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Search(IndexCreationError)', src/libcore/result.rs:997:5
```
Is any suggestions?

**Comment by fdb-hiroshima** [comment]
does the user you are running `plm search init` have enough permissions to create a folder in here?

**Comment by igalic** [comment]
> Is it possible to build a plume with 2 database backend including pg and sqlite, I found with enable all features, plume-cli will refuse to compile

the easiest way would be to provide binaries with different suffixes, and then have an "alternatives" (script or link) point to the preferred / selected version

**Comment by sequencer** [comment]
I found that `plm search` is different to `plm instance` which need to run in the plume directory, because `plm instance` is configuring database use `DATABASE_URL`, while `plm search` is modifying files.
Will it be possible that give a environment variable making `plm search` being able to run anywhere?

**Comment by sequencer** [comment]
> > Is it possible to build a plume with 2 database backend including pg and sqlite, I found with enable all features, plume-cli will refuse to compile
> 
> the easiest way would be to provide binaries with different suffixes, and then have an "alternatives" (script or link) point to the preferred / selected version
I understand, I currently package it to a pg version, and If anyone need, just modify the `PKGBUILD`

**Comment by fdb-hiroshima** [comment]
> Will it be possible that give a environment variable making `plm search` being able to run anywhere?

You can use `SEARCH_INDEX` for that, it needs to point to either an empty directory or the place you want it to create one

**Comment by sequencer** [comment]
https://github.com/sequencer/pkgbuild_plume is able to package to Arch Linux, need to check if database migration is right or not.
I'm going to ask a TU to check this package, and hopefully to push to community repo.
BTW, if version can drop `alpha-1` or `alpha-2`, `PKGBUILD` can handle it better :)

**Comment by fdb-hiroshima** [comment]
I'll test if migrations are run as expected.
In the meantime you can probably put it on AUR

**Comment by sequencer** [comment]
I'm contacting to TU. If not able to put it in community, than I'll put it in AUR.

**Comment by sequencer** [comment]
TU told me that I should make `0.3.0-alpha-2` to `0.3.0a2`
However the `PKGBUILD` logic is following this: 
`0.3.0a1 < 0.3.0a2 < 0.3.0`
I found the version logic is follow this:
`0.2.0a1`, `0.3.0a2`
That may be the only package problem till now.

**Comment by sequencer** [comment]
AUR submitted https://aur.archlinux.org/packages/plume/

**Comment by BaptisteGelez** [comment]
Amazing! Thank you!

**Comment by igalic** [comment]
@sequencer, one of your dependencies is `diesel_cli`, which we don't need any more, having integrated that functionality into `plm`

**Comment by sequencer** [comment]
Fixed.
