### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by m4sk1n** [Plume-org/Plume#58]
Just like in title, it might be challenging, because I haven’t seen any good i18n crate for web, but it’s definitely possible. My Rust knowledge is not enough to start working on it. I will translate the project to Polish when it’s done.

**Comment by asonix** [comment]
The way I'm thinking about doing this in Aardwolf is something along the lines of having a few data types

```rust
#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, PartialEq, Serialize)]
pub enum Lang {
    En,
    Fr,
    ...
}

#[derive(Deserialize, Seriralize)]
pub struct Strings {
    welcome_title: String,
    other_string: String,
    ...
}
```

And then on application start, read language toml files and parse them into some global `HashMap<Lang, Strings>` maybe with `lazy_static`, and panic if any strings are not present for a given language.

**Comment by asonix** [comment]
Maybe a default Strings struct can exist as well if a requested language doesn't exist in the hashmap

**Comment by fdb-hiroshima** [comment]
I've never actually internationalized something, but I don't think a simple hashmap is enought. We may run into situations where we have some string containing numbers, and need to pluralize according to a language's rule (in english, zero is plural, in french it's singular), or just include a string in another ('hello $username, how are you today?') which we can't do with something that simple

**Comment by BanjoFox** [comment]
Am i perhaps missing something or is alpha-numeric not a valid string in Rust?

Granted, "1+3/99" will not calculate but it should still be possible to say

$username = "1+3/99"
println "welcome" $username

and have it come back with:
"welcome 1+3/99"

Right....?

**Comment by m4sk1n** [comment]
Do fluent-rs look good for this?

**Comment by BaptisteGelez** [comment]
I'm not sure it has a good way to support plurals. I think gettext is the way to go: it supports everything we could need (plurals even in languages like Russian, interpolation), is well documented and has a good tooling to make contributing to translation easy. But if you know an alternative with the same characteristics, I'm not against using it.

**Comment by BaptisteGelez** [comment]
@m4sk1n If you want to translate to Polish, it is now possible! I made a translation guide, there is a link in the README.
