### ISSUE TITLE
Differentiate between admin and moderator

### ISSUE THREAD

**Issue by AnaGelez** [Plume-org/Plume#582]
**Is your feature request related to a problem? Please describe.**

There is no way to give someone access to the instance moderation tools without allowing them to change the instance settings too. Also it can be useful for users to be able to know who their admin and moderators are, to contact the right person if they have an issue.

**Describe the solution you'd like**

A distinction between admin and moderator. Considering our needs, I think having a boolean `moderator` field on the `User` model will be enough, we don't need a full role/permission system.

Admins should be able to choose who becomes a moderator.

**~~Describe alternatives you've considered~~**

**Additional context**

[From Loomio](https://framavox.org/d/LUb3JMeX/moderation-tools)

**Comment by fdb-hiroshima** [comment]
As we can assume an admin is also moderator, instead of being two separate boolean these could be 2 variants of an enum (the third being normal user)

**Comment by BaptisteGelez** [comment]
Yes, why not. I know Postgres supports enums, but does SQlite too, or must we use a string?

**Comment by fdb-hiroshima** [comment]
I think we have to use string or a mapping between enum and int (what I did/am doing for lists types)
