### ISSUE TITLE
Banned emails list

### ISSUE THREAD

**Issue by AnaGelez** [Plume-org/Plume#587]
**Is your feature request related to a problem? Please describe.**

Someone can quite easily create hundreds of fake email addresses and register as much accounts on Plume, to spam people. Someone who gets banned can also recreate an account with the same email.

**Describe the solution you'd like**

Being able to have a list of forbidden emails patterns would be useful. It should accept regex, wildcard patterns or something like that, so that if someone tries to generate emails on the fly following a pattern it can easily be stopped.

**~~Describe alternatives you've considered~~**

**Additional context**

[Discussion on Loomio](https://framavox.org/d/LUb3JMeX/moderation-tools)

**Comment by BaptisteGelez** [comment]
Also, I'm thinking about it: we don't currently check if the email that we ask for during registration is valid, we probably should (but this would need its own issue).

**Comment by epsilon-phase** [comment]
Would it suffice, for now, to provide some formatting checking?

It seems like an expedient thing to add while fiddling with the blocklist

**Comment by igalic** [comment]
the easiest way to check for validity of an email address is to send a confirmation link to it

do we currently do that?

**Comment by fdb-hiroshima** [comment]
The email is currently used _only_ for password reset. It's (laxly) checked to be valid on signup, but no mail is sent to it

**Comment by igalic** [comment]
we should probably change that. some time in the future
