### ISSUE TITLE
add --version and --help for plume binary

### ISSUE THREAD

**Issue by igalic** [Plume-org/Plume#594]
Thanks to Cargo build caching, it's sometimes really hard to tell which version we're running.

**Describe the solution you'd like**

running `plume --version` should not start the server, but instead just print the version number.
similarly, running `plume --help` should print some basic help on how to run plume successfully, i.e.: from the directory containing your `.env` file and your `static` dir.

**Describe alternatives you've considered**

running `strings plume | grep <version-number>` is not very user friendly

**Comment by papey** [comment]
If that's ok for you, i'll take this one.

What is the needed precision level for --version ? Release version from `Cargo.toml` ? Last commit SHA ? Both ?

To be sure I correctly understand, can you clarify what you mean by 

> from the directory containing your .env file and your static dir.

Thanks !
