### ISSUE TITLE
Consider using Shrinkwrap for wrapper types

### ISSUE THREAD

**Issue by igalic** [Plume-org/Plume#597]
we have a lot of wrapper types in places — such as `Id(u32)`, or `SafeString(String)` which require a lot of boilerplate code.

Code that would be perfect for macro use!

Even better, when someone already made such macros: [shrinkwrap](https://crates.io/crates/shrinkwraprs)

**Comment by igalic** [comment]
we could also (instead?) use [diesel-derive-newtype](https://crates.io/crates/diesel-derive-newtype)

**Comment by BaptisteGelez** [comment]
I think these two crates don't derive the same traits. Like `shrinkwrap` is more for `std` traits like `Deref`/`AsRef`/etc, and `diesel-derive-newtype` is for diesel (who would have guessed).
