### ISSUE TITLE
Arm32 compile fails on nix dependency

### ISSUE THREAD

**Issue by mcrosson** [Plume-org/Plume#611]
The arm32 build fail with the linked error. It seems this is fixed in an updated version of nix. Would it be possible for the nix version to be bumped to get arm32 support back?

Build errors: https://paste.lollipopcloud.solutions/?1185aefe37177bb9#uOSxiTy5YkA/ApGmpVHj0BZQ47equRKpVt1FkRHCAJM=

Nix issue: https://github.com/nix-rust/nix/issues/1057

**Comment by mcrosson** [comment]
Looks like the below updates fix the arm32 builds. Would it be possible for someone to update the dependencies?

I'm not sure how to do it correctly for a PR otherwise I would have submitted a PR.

```
root@ff6e36226ece:/app# cargo update --package atomicwrites
    Updating crates.io index
    Updating atomicwrites v0.2.2 -> v0.2.3
    Updating libc v0.2.55 -> v0.2.58
    Updating nix v0.11.0 -> v0.14.1

root@ff6e36226ece:/app# cargo update --package ctrlc
    Updating crates.io index
    Updating ctrlc v3.1.2 -> v3.1.3
    Removing nix v0.13.0

cargo update --package nix
    Updating crates.io index

```

**Comment by fdb-hiroshima** [comment]
if it works with just those 3 commands runned, you can git add Cargo.lock, commit and push, it should be enough

**Comment by mcrosson** [comment]
Looks like the builds are back to green with arm32, closing the issue.

Thank you @fdb-hiroshima for all the help!
