### ISSUE TITLE
Blogs aren't scoped to a user

### ISSUE THREAD

**Issue by zcdunn** [Plume-org/Plume#62]
Using my Plume account, @0x1C3B00DA@baptiste.gelez.xyz, I created a blog here: 
https://baptiste.gelez.xyz/~/FederationTesting/. 

As you can see at that link, @Trinity@baptiste.gelez.xyz was able to write an article in that blog. I think this might not be what users expect. A blog should probably be private to a user, by default, and the blog owner can allow others to write to the blog.

**Comment by fdb-hiroshima** [comment]
Whoops, sorry I did not want to ennoy you by writing there, it was the first blog I saw and I thought it was generic/public so I published in it :/

**Comment by zcdunn** [comment]
@fdb-hiroshima No worries! I wasn't annoyed at all. It was just a good example for the bug I was posting. Feel free to keep posting there.
