### ISSUE TITLE
Better logging

### ISSUE THREAD

**Issue by elegaanz** [Plume-org/Plume#623]
**Is your feature request related to a problem? Please describe.**

For the moment our logging is mainly based on `println!` and `dbg!`, which is far from ideal, as it may fill the logs with quite unnecessary and hard to filter messages (and also they are missing a lot of useful info, like the time at which they were written).

**Describe the solution you'd like**

Using the `log` crate with one of its "frontend" (I don't know what the exact term is), like `env_logger`. Maybe we could even add a feature to let people choose which logger "frontend" to use?

**~~Describe alternatives you've considered~~**

**~~Additional context~~**

**Comment by fdb-hiroshima** [comment]
I think we should stick to `log` as it's already used by both Rocket and Tantivy, allowing to choose would mean some logs would go at a place and others somewhere else, which does not make much sens for the end user
