### ISSUE TITLE
Can only start plume with contents of .env file in single argument call to "plume"

### ISSUE THREAD

**Issue by iamdoubz** [Plume-org/Plume#626]
## What is happening
In the docs provided, it says to create a .env file in the place where you built Plume. From following the instructions, I think that this location is `/home/plume/Plume/.env` but am unsure. With all my variables in this file, when I run any command, i.e. `plm migration run` it says that the database cannot be connected to. So, when I add the `DATABASE_URL` in front of these commands, it works just fine.

## What I need help with
Where, exactly, given that I am running Plume with a dedicated user named "plume" and have compiled from source for Ubuntu 16.04, do I put my .env file so that Rust? Plume? app can read these variables without me having to put them all in an extremely long argument to launch and run Plume?

### Arguments used to install Plume
```
# Install Rust first...
curl https://sh.rustup.rs -sSf | sh

# Git latest version
git clone https://github.com/Plume-org/Plume.git
cd Plume

# Next Build the front-end
cargo install cargo-web&&cargo web deploy -p plume-front

# Build the back-end, replacing DATABASE either with postgres or sqlite
cargo install --no-default-features --features postgres --force&&cargo install --no-default-features --features postgres --path plume-cli --force
```
### Other items

1. Ubuntu 16.04
2. PostgresSQL

## Good to knows
My instance actually _works_, I just want to be able to use the "configuration" file the way it was meant to be used. I am using custom logo, that works, email server, that works, and would like to use custom port (not 7878). Thanks for all your help and for creating Plume!

**Comment by fdb-hiroshima** [comment]
the actual position where `.env` have to be is the directory from where `plm`/`plume` will be run, the documentation might be inaccurate, can you point me to the exact page there is a mistake?

**Comment by iamdoubz** [comment]
Thank you for such a quick response.

I have been running `plm`/`plume` from the git directory `/home/plume/Plume`

I have the .env file in three locations. Each results with the same error of:
```
plume@server:~$ plume
thread 'main' panicked at 'main: database pool initialization error', src/libcore/option.rs:1034:5
```
### Locations
`/home/plume/.cargo/bin/.env`
`/home/plume/.env`
`/home/plume/Plume/.env`

### Documentation Link
[https://docs.joinplu.me/installation/config](https://docs.joinplu.me/installation/config) at line `Before starting Plume, you’ll need to create a configuration file, called .env. Here is a sample of what you should put inside.`
And also from the [Useful Environment Variables](https://docs.joinplu.me/environment) page.

### Note:
From the second link, I may or may not have from the directory /home/plume/Plume ran `cargo run` because I could not get the .env to work at that time if that helps.

**Comment by fdb-hiroshima** [comment]
What is the value of `pwd` when you try to run plume?

**Comment by iamdoubz** [comment]
When I run `plume` from `/home/plume` or `/home/plume/Plume` without any pre-arguments, I get `thread 'main' panicked at 'main: database pool initialization error', src/libcore/option.rs:1034:5`

Would you like me to run it with `RUST_BACKTRACE=1 plume`?

**Comment by fdb-hiroshima** [comment]
The backtrace won't show anything useful, for some reason we discard any error when trying to read .env. This can actually fail in many ways, file not found, no read permission (wrong user), syntax error in the file...
The easiest might be for you to run a patched plume which actually fail when erroring on .env
I've made a branch (`test/dotenv_error`) you can pull, checkout and install which will explicitly fail when it can't read .env, with hopefully something helping.

**Comment by iamdoubz** [comment]
That was extremely helpful actually:

> syntax error in the file...

So, according to the [Useful Environment Variables](https://docs.joinplu.me/environment) page, I can explicitly state what server and port to use using `ROCKET_ADDRESS` and `ROCKET_PORT`. If I comment those two lines out in the .env file, guess what happens? It _works_! 

So, I think maybe you or the Plume team need to verify whether or not using the non-standard port actually works in this case?

For now, thankfully I do not have any other server software running on port 7878, I will just use the standard server and port until I hear I can do so otherwise. Again, thank you for all your help!

Now to set up and configure init...

**Comment by fdb-hiroshima** [comment]
I can assure you it work, my local instance run of 8000. Could you send the failing .env as an attachment? There is probably something like an unbreakable space or something like that. And the parser is actually very lenient, you can provide it unknown variables it won't say anything at all

**Comment by iamdoubz** [comment]
Sure thing:

```
# Postgres SQL setup
DATABASE_URL=postgres://plume:password@127.0.0.1:5432/plume

# For PostgreSQL: migrations/postgres
MIGRATION_DIRECTORY=migrations/postgres

# The domain on which your instance will be available
BASE_URL=my.plume.url

# Secret key used for private cookies and CSRF protection `openssl rand -base64 32`
ROCKET_SECRET_KEY=supersecret
ROCKET_ADDRESS 127.0.0.1
ROCKET_PORT 9092

# Mail settings
MAIL_SERVER=my.plume.url
MAIL_USER=admin@my.plume.url
MAIL_PASSWORD=emailpassword
MAIL_HELO_NAME=my.plume.url
MAIL_ADDRESS=no-reply@my.plume.url

# Custom icons
PLUME_LOGO=icons/custom/logo/plume.png
PLUME_LOGO_FAVICON=icons/custom/logo/plume32.png
PLUME_LOGO_48=icons/custom/logo/plume48.png
PLUME_LOGO_72=icons/custom/logo/plume72.png
PLUME_LOGO_96=icons/custom/logo/plume96.png
PLUME_LOGO_144=icons/custom/logo/plume144.png
PLUME_LOGO_160=icons/custom/logo/plume160.png
PLUME_LOGO_192=icons/custom/logo/plume192.png
PLUME_LOGO_256=icons/custom/logo/plume256.png
PLUME_LOGO_512=icons/custom/logo/plume512.png

```

**Comment by fdb-hiroshima** [comment]
there is no `=` for `ROCKET_ADDRESS` and `ROCKET_PORT`

**Comment by iamdoubz** [comment]
As soon as I pasted and commented, I realized what it was from this:

> There is probably something like an unbreakable space or something like that.

EVERYTHING in this file has an `=`

My `ROCKET_ADDRESS` and `ROCKET_PORT` did not...

Again, thank you so make for helping me help myself. For anyone else that may or may not stumble across this, my .env file needed to be in `/home/plume/Plume`

**Comment by BaptisteGelez** [comment]
May I close this issue? Or at least update its title to remind us to panic if the .env contains an error?

**Comment by iamdoubz** [comment]
Yes you may close the issue. I would also change the title to add .env errors to log/etc.

Thanks again!

**Comment by fdb-hiroshima** [comment]
I've made an issue that is more to the point, but target the same underlying problem
