### ISSUE TITLE
Comprehensive Apache2 .conf file

### ISSUE THREAD

**Issue by iamdoubz** [Plume-org/Plume#628]
I just wanted to add to the default documentation of [how to set up a reverse proxy for Plume using Apache](https://docs.joinplu.me/installation/proxy/apache) with my apache.conf file that has been growing in size and complexity as I add more and more services to my web server. It is insanely, way over the top for most people, but I feel that you can learn an awful lot/add features to your webserver that you may or may not be missing.

## Requirements
1. Apache version > 2.4
2. A bunch of mod's enabled (headers, proxy, proxy_balancer, proxy_http, proxy_wstunnel, rewrite, lbmethod_byrequests and there may be others but those are the ones I know off the top of my head)
3. Protocols h2 http/1.1 needs `apachectl -V` 2.4.17 and higher...

## Note
Again, this isn't a bug or really a feature request, just more of an FYI.

## Updated July 1, 2019
Thanks to @igalic for the constructive feedback and suggestions.
## Update July 2, 2019
Added a regexp match for the cache items thanks to @fdb-hiroshima 

## Apache .conf file contents

```apache
    DEFINE plume_url 127.0.0.1
    DEFINE plume_port 7878
    DEFINE public_url plu.me
    DEFINE email admin@plu.me
    DEFINE files_loc /home/plume/Plume
    ServerTokens Prod
    SSLStaplingCache "shmcb:${APACHE_LOG_DIR}/stapling-cache(150000)"
    SSLSessionCache "shmcb:${APACHE_LOG_DIR}/ssl_scache(512000)"
    SSLSessionCacheTimeout 300
<VirtualHost *:80>
    ServerName ${public_url}
    #DocumentRoot /var/www/dummy
    ServerAdmin ${email}
    RewriteEngine On
    RewriteCond %{SERVER_NAME} =${public_url}
    RewriteCond %{HTTPS} off
    RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
<VirtualHost *:443>
    ServerName ${public_url}
    #DocumentRoot ${files_loc}/static
    ServerAdmin ${email}
    SSLEngine On
    SSLCertificateFile /etc/letsencrypt/live/${public_url}/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/${public_url}/privkey.pem
    #Include /etc/letsencrypt/options-ssl-apache.conf
### Forbid the http1.0 protocol ###
    Protocols h2 http/1.1
### Bunch of magic goes here ###
    Timeout 60
    ProxyRequests Off
    ProxyPreserveHost On
    ProxyTimeout 600
    ProxyReceiveBufferSize 4096
    SSLProxyEngine On
    RequestHeader set Front-End-Https "On"
    SSLUseStapling On
    SSLStaplingResponderTimeout 5
    SSLStaplingReturnResponderErrors Off
### Harden security ###
    ServerSignature Off
    SSLCompression Off
    SSLSessionTickets Off
    RequestHeader set X-Forwarded-Proto 'https' env=HTTPS
    Header always set Strict-Transport-Security "max-age=15552000; preload"
    Header always set X-Content-Type-Options nosniff
    Header always set X-Robots-Tag none
    Header always set X-XSS-Protection "1; mode=block"
    Header always set X-Frame-Options "SAMEORIGIN"
    Header always set Referrer-Policy "strict-origin-when-cross-origin"
 ## Extremely untested Content-Security-Policy ##
    Header always set Content-Security-Policy-Report-Only "default-src 'self' https:; font-src 'self' data: ${plume_url} ${public_url}; media-src 'self' ${plume_url} ${public_url}; script-src 'self' 'unsafe-inline' ${plume_url} ${public_url}; style-src 'self' ${plume_url} ${public_url}; img-src 'self' data: blob: ${plume_url} ${public_url}; worker-src *; frame-src 'none'; connect-src 'self' wss: https: ${plume_url} ${public_url};"
 ## Use next two for very secure connections ##
    #SSLCipherSuite EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
    #SSLProtocol All -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
 ## Use next two for secure connections and supports more endpoints ##
    SSLCipherSuite EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:ECDHE-RSA-AES128-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA128:DHE-RSA-AES128-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA128:ECDHE-RSA-AES128-SHA384:ECDHE-RSA-AES128-SHA128:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA128:DHE-RSA-AES128-SHA128:DHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA384:AES128-GCM-SHA128:AES128-SHA128:AES128-SHA128:AES128-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4
    SSLProtocol All -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
    SSLHonorCipherOrder On
### Actually proxy the traffic and really the only important part ###
    ProxyPass / http://${plume_url}:${plume_port}/
    ProxyPassReverse / http://${plume_url}:${plume_port}/
### Maybe need these but unsure ###
    #Options -Includes -ExecCGI
    #LimitRequestBody 512000
    #FileETag None
    #TraceEnable Off
 ## Set caching on image files for 2 weeks
    <FilesMatch ^/static/media/(.*)$>
        Header append Cache-Control "public, max-age=1209600, immutable"
    </FilesMatch>
    AliasMatch ^/static/media/(.*)$ ${files_loc}/static/media/$1
 ## Set caching on static files for 2 weeks
    <FilesMatch ^/static/cached/([^/]*)/(css|fonts|icons|images)/(.*\.(js|css|woff2|otf|ttf|woff|eot|png|jpe?g|gif))$>
        Header append Cache-Control "public, max-age=1209600, immutable"
    </FilesMatch>
    AliasMatch ^/static/cached/([^/]*)/(css|fonts|icons|images)/(.*\.(js|css|woff2|otf|ttf|woff|eot|png|jpe?g|gif))$ ${files_loc}/static/$2/$3
</VirtualHost>
```

**Comment by igalic** [comment]
might i suggest not to use mod_rewrite, where a simple directive may suffice?

you can replace this block

```apache
### Forbid the http1.0 protocol ###
    RewriteEngine On
    RewriteCond %{SERVER_PROTOCOL} ^HTTP/1\.0$
    RewriteCond %{REQUEST_URI} !^/path/to/403/document.html$
    RewriteRule ^ - [F]
```

with [Protocols](http://httpd.apache.org/docs/2.4/mod/core.html#protocols)

Caching:

```apache
 ## Set caching on static files for 2 weeks
    <FilesMatch ^/static/cached/5d3b8b65/(css|fonts|icons|images)/(.*\.(js|css|woff2|otf|ttf|woff|eot|png|jpe?g|gif))$>
        Header append Cache-Control "public, max-age=1209600, immutable"
    </FilesMatch>
```
okay, yes, prefect! except, that hash (`5d3b8b65`) changes in releases (if, and only iff) any of the files has changed

but here,

```apache
    AliasMatch ^/static/cached/5d3b8b65/(css|fonts|icons|images)/(.*\.(js|css|woff2|otf|ttf|woff|eot|png|jpe?g|gif))$ ${files_loc}/static/$1/$2
```

you're forcing browsers to see each new version of those files under the same URL. That completely undermine Plume's own caching strategy, and your own setting of caching headers, because now you have to think of how to invalidate the browser cache!

which you can't.

i'd have more to say, but i'm lying in bed, typing this on my phone

oh, get rid of the `<IfModule>` wrapper : you're in control of the config, and the whole thing doesn't make sense without mod_ssl

**Comment by iamdoubz** [comment]
@igalic FINALLY!... someone with constructive feedback!!! I was hoping someone would actually _read_ one of the many of these that I have posting, who actually understands what most of the items mean, and provide better explanation on how to better the configuration! I will make your changes...

`AliasMatch`

> you're forcing browsers to see each new version of those files under the same URL
Wonderful explanation as I really did not understand what that specific line meant.

```
### Forbid the http1.0 protocol ###
    RewriteEngine On
    RewriteCond %{SERVER_PROTOCOL} ^HTTP/1\.0$
    RewriteCond %{REQUEST_URI} !^/path/to/403/document.html$
    RewriteRule ^ - [F]
```

> with [Protocols](http://httpd.apache.org/docs/2.4/mod/core.html#protocols)

I had seen this before, but not with multiple protocols. I was trying to avoid disabling the http2 protocol and now that I have actually _read_ the docs now, this makes since.

> okay, yes, prefect! except, that hash (5d3b8b65) changes in releases (if, and only iff) any of the files has changed

I knew that this would be a problem and forgot to add a note for it.. which I will add above.

**Comment by fdb-hiroshima** [comment]
>  Note: the "5d3b8b65" will change from release to release if the files themselves get updated
 Be sure to change it/check if the release number changes!!!

I've never actually configured an Apache server, but path seems to support regexp, so can't you just match `([^/]*)`? I think what you did would not break, resources would just get read from Plume instead of the file system after an update

```apache
# match any cache id, correct id of matches to account for the new capturing group
AliasMatch ^/static/cached/([^/]*)/(css|fonts|icons|images)/(.*\.(js|css|woff2|otf|ttf|woff|eot|png|jpe?g|gif))$ ${files_loc}/static/$2/$3
```

**Comment by igalic** [comment]
i would completely skip this bit
because it makes your browser cache files that may be outdated

**Comment by fdb-hiroshima** [comment]
they are cached in a "namespace" that is discarded as soon as a file change. It's not optimal in terms of storage usage for the browser (having copy of the same file in different namespaces, although I guess there might be some deduplication). This is exactly what Plume is doing here https://github.com/Plume-org/Plume/blob/3d27e283ad68510092d4dae2a8bfc83caba3ad0a/src/routes/mod.rs#L171-L174
It's just with one indirection level less (apache->file instead of apache->plume->file)

**Comment by iamdoubz** [comment]
> i would completely skip this bit
> because it makes your browser cache files that may be outdated

I knew about this, and that is why I made the cache of 2 weeks as opposed to 1 year.

> can't you just match ([^/]*)?

Great idea. I will add to above. I got the three lines in question here from Peertube apache2 config file. It, in theory, marginally increases load speed at the cost of maybe missing an updated css or icon file. In that case, you can simply remove those two options from the line in your config.
