### ISSUE TITLE
Blog naming issues

### ISSUE THREAD

**Issue by fdb-hiroshima** [Plume-org/Plume#63]
Blog can be created multiple time, by one or multiple persons.
Also even if blog name is slighlty different, one can create a blog with the same in-url name (by using certain chars such as dots or slashes in blog name).
Using the same set of chars it is possible to create a blog which have no in-url name and is thus not accessible (but which is still shown in the dashboard, with an invalid link)

**Comment by fdb-hiroshima** [comment]
The third part of the issue is not resolved yet. I'll push something shortly to fix it.

**Comment by BaptisteGelez** [comment]
Oops, sorry forgot about it.
