### ISSUE TITLE
Not able to register an account

### ISSUE THREAD

**Issue by bodems** [Plume-org/Plume#635]
I am not able to register an account, neither on fediverse.blog nor on cafe.sunbeam.city. I type in my registration data in Firefox, click "create your account", it loads something and the page looks exactly like before I clicked the create button. I also tried this with a freshly new installed Chromium with no additional plugins. Any idea about this?
**Edit:** Of course I am not receiving any registration mail.

- **Plume version:** At least 0.3.0 and 0.2.0
- **Operating system:** OpenBSD 6.5, FreeBSD 12
- **Web Browser:** Firefox 66.0.2, Chromium 73

**Comment by marek-lach** [comment]
Plume does not currently send any confirmation emails yet.

You simply register and then try logging in with the details that you registered when the page is reloaded.

**Comment by bodems** [comment]
So you can't see if the registration was successful or not? I am also not able to login, it says "Invalid username, or password". When I try the password reset I am not receiving any mail.

**Comment by marek-lach** [comment]
> So you can't see if the registration was successful or not? I am also not able to login, it says "Invalid username, or password". When I try the password reset I am not receiving any mail.

You should still be redirected to the login page after registraation. There's just no confirmation email.
The bug you describe is present on fediverse.blog at the moment, you're right.

I tested plume.nixnet.xyz, where the registration works just fine.

**Comment by BaptisteGelez** [comment]
It is because of a federation bug with plume.mastodon.host… It happens regularly. The issue should be fixed on fediverse.blog now. Sorry.

I will try to submit a fix…

**Comment by bodems** [comment]
Many thanks!

**Comment by igalic** [comment]
> Plume does not currently send any confirmation emails yet. The account is created without any confirmation.
>
> You simply register and then try to log in with the details that you registered, once the page is reloaded.


this sounds like a privacy concern that should be fixed ASAP.

**Comment by TomatDividedBy0** [comment]
Can confirm this is no longer an issue on fediverse.blog

**Comment by AnaGelez** [comment]
The federation issue was fixed on plume.mastodon.host's side. But it would still be good to fix the actual issue which is: `User`s coming from federation may have empty `ap_url`/`inbox_url`/`outbox_url`/`followers_endpoint`, which will make any new account violate the `UNIQUE` constraint on these fields (since for a very short time, these accounts have empty string values for these fields too).
