### ISSUE TITLE
404 on the cached data

### ISSUE THREAD

**Issue by commagray** [Plume-org/Plume#645]
Hi.

I use :latest Docker images from the Docker Hub. After a6c84daa1a242246ac01260eb9bc201dd6e47830 theming got broken.

![image](https://user-images.githubusercontent.com/27947961/63451480-fcd6b980-c44c-11e9-87f7-93047577d40f.png)

`<link rel="stylesheet" href="/static/cached/77f3b7ab/css/default-light/theme.css" />` in the page source points to nowhere and returns 404. But, for instance, `<link rel="icon" type="image/png" href="/static/cached/77f3b7ab/icons/trwnh/feather-filled/plumeFeatherFilled64.png">` works fine.

An instance to poke with a stick: https://gospel.sunbutt.faith

I use Traefix for exposing Plume to the outer Internet via HTTPS and Caddy for reverse proxy.

**Comment by AnaGelez** [comment]
It is not your fault, I had this issue too. I will submit a patch in a few hours normally.
