### ISSUE TITLE
Margins are too narrow on mobile

### ISSUE THREAD

**Issue by marek-lach** [Plume-org/Plume#655]
This is not a high priority issue, but compared with the old theme, the left/right margins of a blog post are too narrowly close to the edges of the screen on mobile, especially on the 21:9 aspect ratio screens etc...

You can see the old margins pre ##624:

![IMG_0101](https://user-images.githubusercontent.com/45913977/63687588-46385780-c805-11e9-8d8a-d79081df40e7.PNG)

And after:

![IMG_0100](https://user-images.githubusercontent.com/45913977/63687630-5cdeae80-c805-11e9-9880-cae25ee39039.PNG)

I have not seen any actual text being cropped just yet, but it'd be a good idea to have some small `margin` distance from the display's edges.

- **Plume version:** latest commit
- **Related issues:** #650
- **Operating system:** iOS 12/iPhone X, but I've also tested it on Android 9
- **Web Browser:** iOS Safari, and also Firefox and Chrome for Android

**Comment by marek-lach** [comment]
Closed by #662

**Comment by AnaGelez** [comment]
Sorry, but I reopen for the moment, as long as the PR has not been merged.
