### ISSUE TITLE
Please remove the file rust-toolchain or use a better version

### ISSUE THREAD

**Issue by iamdoubz** [Plume-org/Plume#670]
After installing rust using `curl https://sh.rustup.rs -sSf | sh`, the version is `rustc 1.37.0`. After you then download Plume, enter the directory and start building and compiling, it downloads Rust version "nightly-2019-03-23-x86_64-unknown-linux-gnu" which is outline in the file "rust-toolchain". This leads to the compilation error down the line at `cargo web deploy -p plume-front --release` which produces the errors: 
```
error[E0412]: cannot find type `NonZeroI8` in module `num`
error[E0412]: cannot find type `NonZeroI16` in module `num`
error[E0412]: cannot find type `NonZeroI32` in module `num`
error[E0412]: cannot find type `NonZeroI64` in module `num`
error[E0412]: cannot find type `NonZeroIsize` in module `num`
error[E0412]: cannot find type `NonZeroI128` in module `num`
```

- **Plume version:** You can find it in the footer of your instance. If you know the exact commit, please also add it.
Haven't installed it yet.
- **Operating system:**
Ubuntu 18.04
- **Web Browser:**
Chrome, Firefox, Internet Explorer, Edge, Edge Beta and Vivaldi,.

**Comment by fdb-hiroshima** [comment]
run `cargo +stable web deploy -p plume-front --release` instead. We are aware of this, we tag a compiler because things breaks in nightly, so we will definitely not remove rust-toolchain, and we will probably upgrade the compiler only when we know which version rocket (a major dependency) will require. However we should probably tag a second, more up to date, compiler, for the wasm part

**Comment by iamdoubz** [comment]
From which or instead of which step?

8. Install Plume and CLI tools (~12 minutes to build and compile)
    a. `cargo +stable install diesel_cli --no-default-features --features postgres --version '=1.3.0'`
9. Build the front-end (~22 minutes to build and compile)
    a. `cargo install cargo-web`
    b. `cargo web deploy -p plume-front --release`

**Comment by iamdoubz** [comment]
You can close this if you'd like. I [made a guide](https://github.com/Plume-org/Plume/issues/671) for every step how I got it to work.... Should really update the install docs....
