### ISSUE TITLE
Don't split sentences for translations

### ISSUE THREAD

**Issue by AnaGelez** [Plume-org/Plume#675]
@ryonakano reported on Crowdin that this sentence was not translatable to Japanese because of the different ordering of the words in the Japanese grammar: https://github.com/Plume-org/Plume/blob/4b205fa995a6935a2512a9725d84635e889db48e/templates/session/password_reset_request_expired.rs.html#L8

There are probably a lot of sentences like that, and I think we could just have one string containing the HTML markup, because Crowdin is probably smart enough to hide it/display it as "untranslatable".

**Comment by ryonakano** [comment]
I checked all strings and guess it's only here that split one sentence to two.
