### ISSUE TITLE
I can't run migration 2019-04-28-201506_create_tantivy_index

### ISSUE THREAD

**Issue by Your-New-SJW-Waifu** [Plume-org/Plume#679]
I'm trying to setup a new instance but I got to the part about running migrations. Everything before it worked fine but I'm stuck at `migration 2019-04-28-201506_create_tantivy_index`. It gust gives the error `Received an empty query`.  
My only guess is that it's because there isn't really anything in the DB yet since this is a new instance and it was expecting something.

- **Plume version:** Master commit b488253
- **Operating system:** Arch
- **Database:** Postgres

**Comment by AnaGelez** [comment]
Can you install "plm"/"plume-cli" if not already done, and try with `plm migration run` please?

**Comment by Your-New-SJW-Waifu** [comment]
That resolved it. Thanks!
