### ISSUE TITLE
Empty timelines after update

### ISSUE THREAD

**Issue by EliotBerriot** [Plume-org/Plume#692]
After pulling `plumeorg/plume:latest` (which maps to https://hub.docker.com/layers/plumeorg/plume/latest/images/sha256-a64a3306468d72c947f3c4f1aeb73d8f0431f8f89f0201b596a6b889a66a024b) today, and running `plm migration run` in my Docker container, the service is restarted and working but all the timeline pages show no entries, e.g at https://blog.funkwhale.audio/timeline/1:

![image](https://user-images.githubusercontent.com/1970915/68205745-4904b500-ffcb-11e9-865a-dbfb6f81f36f.png)

While we definitely have corresponding data in the database.

I dont see anything worrying in the server logs, but I can definitely dig if you give me some instructions :)

- **Plume version:** f0846ff5465e3e28807570f0110437098f60efa1

**Comment by epsilon-phase** [comment]
What happens when you try to search? Do posts show up? As they ought to.

**Comment by EliotBerriot** [comment]
Search form doesn't seem to work at all (all fields are required, so I cannot trigger a search, but this is probably unrelated):

![image](https://user-images.githubusercontent.com/1970915/68285671-fdf8a980-007f-11ea-893f-04b53fdc3671.png)

Visiting https://blog.funkwhale.audio/search?q=funkwhale by hand yields appropriate results though.

**Comment by AnaGelez** [comment]
OK, so the issue simply is that the migration that creates the timeline doesn't fill them. I'll try to submit a fix, and to add a command to `plm` to re-generate timelines in case there are issues like that.
