### ISSUE TITLE
Markdown parser is parsing @mentions inside a markdown ```code block```

### ISSUE THREAD

**Issue by edgarogh** [Plume-org/Plume#699]
I have an article containing a code block with a CSS media query whose syntax starts with `@media` and it is parsed as a mention linking to non-existing user 'media'. I expect code blocks to be completely exempted from further parsing.

[live example](https://plume.edgarogh.fr/~/Dev/little-article-s-brother/)

- **Plume version:** 0.3.0 (installed using the instructions on joinplu.me on the 16th nov. 2019), but hasn't been fixed since according to @AnaGelez (shame on her if she was wrong :smiling_imp:)

**Comment by AnaGelez** [comment]
The # may also be interpreted as hashtags (I didn't checked tho), which may be an issue for languages like C.

**Comment by edgarogh** [comment]
Yup `#`s parsed as hashtags too https://plume.edgarogh.fr/~/Dev/yet-another-test

**Comment by epsilon-phase** [comment]
This is, notably, fixed by accident in https://github.com/Plume-org/Plume/pull/691#issue-336583050 but that is blocked until the build can be fixed. :/
