### ISSUE TITLE
No theme at all on "Default theme"

### ISSUE THREAD

**Issue by Kekun** [Plume-org/Plume#701]
I had the light theme, I modified my profile, the theme was "Default theme" and I didn't touch the combobox at all, I saved my changes, I had no theme.

When explicitly setting another theme, it works, when explicitely setting it back to "Default theme", I have no theme again.

![Capture d’écran de 2019-11-24 19-17-55](https://user-images.githubusercontent.com/2536339/69499169-918b0080-0eef-11ea-96eb-5892a33cef90.png)

- **Plume version:** 0.3.0
- **Operating system:** Fedora Silverblue 31.20191107.0
- **Web Browser:** GNOME Web 3.34.0-18-g574f7196c (current nightly)

**Comment by marek-lach** [comment]
For context: https://bugs.launchpad.net/ubuntu/+source/epiphany-browser/+bug/173147

**Comment by AnaGelez** [comment]
If this bug doesn't come from Plume but from GNOME Web, I'm closing this issue. If someone can reproduce with another browser/engine, I will reopen it.

**Comment by Kekun** [comment]
The issue you refer to is:
- not on GNOME Web's bug tracker but on Ubuntu's,
- 12 years old,
- closed as invalid since more than 9 years.

And here is a screenshot of the same issue repeated with the very same steps in Firefox 70.0 as packaged in Fedora 31.

![Capture d’écran de 2019-12-10 09-18-47](https://user-images.githubusercontent.com/2536339/70508354-97f3bc00-1b2e-11ea-90d6-2048f1e34c53.png)

**Comment by AnaGelez** [comment]
Ok, sorry you are right, I'm reopening.

**Comment by Kekun** [comment]
Thanks! :)

**Comment by marek-lach** [comment]
Very generic things that may, (or may not) help:
- Declaring the type="text/css" explicitly, linking to the theme's scss files
- Edit comments in stylesheets from // format to  /* ... */

**Comment by verymilan** [comment]
It would be amazing to put a new release out, even if only for this, as it confuses the users quite a lot...
