### ISSUE TITLE
Articles are not dated in Atom feeds

### ISSUE THREAD

**Issue by Kekun** [Plume-org/Plume#703]
I moved from Blogger to https://fediverse.blog/ recently, and I updated my adress on Planet GNOME: https://gitlab.gnome.org/Infrastructure/planet-web/commit/8eb9b0d5f6f70da7821b2a24453355e3b9c44746.

Problem: my only article is always at the top of http://planet.gnome.org/ and has a wrong date, that's because the planet doesn't have the info to properly date my article, and that's because there is no time info in the Atom feed: https://fediverse.blog/~/AdrienPlazas/atom.xml.

- **Plume version:** 0.3.0

**Comment by Kekun** [comment]
I disabled my blog from Planet GNOME until this is fixed: https://gitlab.gnome.org/Infrastructure/planet-web/merge_requests/32.

**Comment by fdb-hiroshima** [comment]
I think this is a duplicate of #673 , could you close the issue if this is the case, or explain how it's different?

**Comment by Kekun** [comment]
I don't know Atom so I can't exactly tell, but it seems a lot like a duplicate, thanks! :) Closing.
