### ISSUE TITLE
Content Notes for blog posts

### ISSUE THREAD

**Issue by thorsten-panknin** [Plume-org/Plume#710]
People can enter a content note for comments, but I cannot enter CNs as an author for my blog posts (or even my blog as a whole).

Similar to Mastodon, a field for CNs which when filled blurs or hides the actual content of the blog post. A button for revealing the content could be placed at the top of the hidden content.

I'm on the fediverse.blog instance which uses 0.3.0 of Plume.

**Comment by thorsten-panknin** [comment]
I can use the sub title for CNs for now since it can be used as a teaser on the overview page, too.

**Comment by AnaGelez** [comment]
Do you mean content warning by content note? If so, is it really needed to have both a subtitle and a content warning? Can't the warning/note be included at the end of the subtitle?

**Comment by thorsten-panknin** [comment]
Yeah, after I'd thought of reusing the subtitle for it, it probably suffices. Leaving it to you to close this issue.

**Comment by AnaGelez** [comment]
I'm closing for the moment, but if someone has another argument in favour of this feature I will re-open. Thanks for the suggestion anyway!
