### ISSUE TITLE
Duplicated articles in timelines

### ISSUE THREAD

**Issue by elegaanz** [Plume-org/Plume#711]
When publishing an article, it gets duplicated in timelines after some time.

It looks like duplication happens every time someone likes or boosts the post (from the same instance, or from another one), but I'm not 100% sure.

- **Plume version:** 0.4.0
- **Operating system:** Linux, but not relevant IMO
- **Web Browser:** Firefox Nightly, but not relevant either

**Comment by AnaGelez** [comment]
Probably `plume_models::timeline::Kind` that is not interpreted when it should.

**Comment by AnaGelez** [comment]
OK, I didn't really checked, but these lines seem suspiscious :

https://github.com/Plume-org/Plume/blob/master/plume-models/src/timeline/query.rs#L393
https://github.com/Plume-org/Plume/blob/master/plume-models/src/timeline/query.rs#L400

**Comment by fdb-hiroshima** [comment]
There is no uniqueness constraint on `timeline` (the sql table), so a single post can appear any number of time, for instance if someone you follow boost it. I don't know if it should fail to add it again, or "refresh" the post so it's back on top of your timeline (but not present multiple time). 
Not really related, but having an indicator of it being boost/like, or a classic "post from someone I follow or a list I watch or a keyword or .....", might be interesting (but should be it's own issue)

**Comment by AnaGelez** [comment]
The post should probably be duplicated but only when boosted/likes by someone you follow (and if boosts/likes are "on" for this timeline, which is not even the case here IIRC).

And :+1: for the indicator

**Comment by fdb-hiroshima** [comment]
boosts are on by default for `follow`, and both boost and like are on for `local` and `all` targets. This is easy to change, around line 400-410 of `plume-models/src/timeline/query.rs`

**Comment by AnaGelez** [comment]
Boosts and likes should probably do nothing in "public" timelines actually, and only work for user-specific timelines. They don't make sense in this context IMO.

**Comment by y6nH** [comment]
This seems to be getting worse. When I look at fediverse.blog (Plume 0.4.0), there are seven cards for the article "Most Dangerous Mobile Apps That Can Steal Your Data" in each of the local and federated timelines. I don't follow that blog, and the post has two likes and two boosts, so I'm not sure how it gets to seven. Even stranger, a draft article of mine that isn't even published has *nine* cards in my personal feed. 

I haven't looked at the code, but is this pulling back a new result for every time the article was edited?

**Comment by ksteimel** [comment]
I just tried this out on a test instance I spun up and indeed, even for local articles, when you edit the article it shows up again in both the local and federated feed.

**Comment by irredentist** [comment]
Any progress on a fix for this? It's showing up on an instance I use.

**Comment by Chostakovitch** [comment]
Hello everyone, 
I am also experimenting the same issue ; obviously making `blogId` unique in the `timeline` table will break a lot of stuff and is not a solution.

I am not familiar to Rust and I think that I don't understand the philosophy of Plume. However it is counter-intuitive to have duplicates, especially on the last articles page, so here is my guesses : 
* Each time a post is modified, liked, shared, etc, it generates a new entry in the table `timeline`
* This is more a feature than a bug, because if we think about the Mastodon feed, it makes sense to see boosts, likes and edits of a single toot in the timeline.

As @elegaanz mentioned the timeline should probably have an indicator to tell whether the entry is a new post, a boost, an edit, etc.

Now if I understood correctly, my question is : does it make sense to filter the blog posts before displaying the last articles page, to make them unique, or would it be a hacky way of "solving" this issue ?

Thanks :)

**Comment by elegaanz** [comment]
>     * Each time a post is modified, liked, shared, etc, it generates a new entry in the table `timeline`

Yep, that's what I think too.

>     * This is more a feature than a bug, because if we think about the Mastodon feed, it makes sense to see boosts, likes and edits of a single toot in the timeline.

It would make sense to see what people you follow boosted, not to have the same article twice because someone you don't know boosted it.

> Now if I understood correctly, my question is : does it make sense to filter the blog posts before displaying the last articles page, to make them unique, or would it be a hacky way of "solving" this issue ?

It would be very hacky, and would make it necessary to make a lot of SQL queries (i.e you ask for the 12 last articles, but then you filter out 4 of them because they are duplicates, so you have to ask the database for the 4 next articles, but you still filter two of them… and so on, until you finally have your 12 articles, or you reach the end of the database). So, even if it could work, I would prefer to properly fix this issue.

I will try to find time and motivation to investigate (and maybe fix this bug). I'll post the results here (ping me in a few days if I didn't post anything).

**Comment by Chostakovitch** [comment]
@elegaanz Thanks for taking the time to answer. You're utterly right. Unfortunately I know nothing about Rust and for now I cannot help.

The design goal is still unclear to me. My guess would be :
* The last articles page contains new local blog entries ordered by desc date
* The local feed contains local activity, including likes, shares (+ should maybe have an type indicator)
* The federated feed contains the same elements that the local feed but with all connected instances
* And My feed only contains articles and activity from individual accounts you follow 

I am however not sure that the local/global feeds should display likes, shares etc., but if they don't, there is no difference between last article and local feed. 

What do you think ?

**Comment by elegaanz** [comment]
What is the "last articles page" you are talking about? Otherwise, I do agree with what you say.

**Comment by Chostakovitch** [comment]
@elegaanz "Derniers articles" in French, probably the wrong translation, sry.

**Comment by elegaanz** [comment]
Do you see that on the homepage? Where exactly?

**Comment by Chostakovitch** [comment]
@elegaanz The first tab : https://pic.chosto.me/uploads/big/3e3d9d700e71aacc85a7126436ba845c.jpg
Or maybe it is an outdated tab ? I run v0.4.0

**Comment by elegaanz** [comment]
Oh, okay, sorry. This tab contains the three others actually, so that you can see all the new articles on the same page, both from the local and federated feeds, and from your own feed.

**Comment by Chostakovitch** [comment]
Ok, so this is one of the things that were unclear to me. I am used to "normal" blogs, so I assumed this page would contain only local entries.

So, to summarize, the goal would be :
* First tab = last articles from local and federated feeds ordered by desc date
* Local and federated same as first but split by origin
* "My feed" with only articles from followed accounts, augmented with shares, likes, etc
?

Anyway, If I can help in any way, please tell me.

**Comment by elegaanz** [comment]
Yes, that's it.

**Comment by verymilan** [comment]
Hi, thank you for that fix, sadly [my instance](https://write.tchncs.de/) still got those duplicated entries after upgrading.. may there be some cache i gotta rebuild or something?

**Comment by trinity-1686a** [comment]
There is not really a cache for that, timelines are stored in database. The following incantation may help you if you can access a sql console, however you should backup your database beforehand, just in case.
```sql
DELETE FROM timeline WHERE id NOT IT (SELECT MIN(id) FROM timeline GROUP BY post_id, timeline_id);
```

**Comment by verymilan** [comment]
Thank you very much, it looks healthy now!
