### ISSUE TITLE
0.4.0-alpha-4 release assets

### ISSUE THREAD

**Issue by yalh76** [Plume-org/Plume#714]
https://github.com/Plume-org/Plume/releases/download/0.4.0-alpha-4/plume-postgres.tar.gz and https://github.com/Plume-org/Plume/releases/download/0.4.0-alpha-4/plume-sqlite.tar.gz seems to be .tar.gz in a .zip file

To test it:
```
wget https://github.com/Plume-org/Plume/releases/download/0.4.0-alpha-4/plume-postgres.tar.gz
tar -xvf plume-postgres.tar.gz
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

- **Plume version:** 0.4.0-alpha-4
- **Operating system:** Debian Strech + Windows
- **Web Browser:** None

**Comment by fdb-hiroshima** [comment]
It should be good now. For some reason, archives where actually `.tar.gz.gz`
