### ISSUE TITLE
Simplify the like/reshare section

### ISSUE THREAD

**Issue by BaptisteGelez** [Plume-org/Plume#72]
Our layout for the like and reshare counter/button is quite complicated : we use full sentences where an icon and a number next to it would probably be enough (it is what most apps are doing). It would also also allow us to put them on the same line, next to each other which would be more coherent. But I would like the input of someone who is more experienced than me in designing interfaces.

**Comment by Madeorsk** [comment]
Yes, I don't like the like / reshare section too, I have an idea to improve it that I will suggest soon (probably today?).

But I would prefer to keep a text to describe the action under the icon, for accessibility mainly.

**Comment by Madeorsk** [comment]
What do you think about something like that? ![Example](https://user-images.githubusercontent.com/5805468/41768690-30b15df8-760d-11e8-81ac-55d857e1056e.gif)

**Comment by BaptisteGelez** [comment]
I love the style of the buttons. A bit more of margin between the labels and the circle may be better.

Actually, I feel like the wording of the labels is really weird, especially when nobody liked/republished. You don't say "0 people liked this article", but "Nobody liked this article". That's why just a counter would be better for me.

But I understand that it's not ideal for accessibility. We should probably try to find an `aria-` property that could be used to provide a true label for those who need it (even if the wording would still be weird for them :confused:).

**Comment by Madeorsk** [comment]
#84
