### ISSUE TITLE
HTTP 502 errors after moving instance to a new server

### ISSUE THREAD

**Issue by busshimoe** [Plume-org/Plume#738]
I recently had to reinstall my server running my Plume instance.  I restored the database from backup and reinstalled Plume from source.  All of this worked, until I published a new post, at which point Plume started throwing HTTP 502 errors.  Trying to refill the search index (which I guessed might be part of the problem) gives the following error.
```
$ plm search refill
Configuration read from /home/plume/Plume/.env
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Search(IndexOpeningError)', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

- **Plume version:** commit 458baf5f78daec1b823e0bbd17eaa96c23ae92f8
- **Operating system:** Ubuntu 18.04.3 LTS x86_64

**Comment by AnaGelez** [comment]
Try to stop Plume, then do `plm search unlock` and `plm search refill`. It may help.

**Comment by busshimoe** [comment]
Same issue.  I think the root issue is probably something else, but I'm not sure what it could be.

**Comment by AnaGelez** [comment]
Try to delete the search index directory, and recreate it with `plm search init`.

**Comment by busshimoe** [comment]
OK wow, that worked, thank you!
