### ISSUE TITLE
Rename reshares

### ISSUE THREAD

**Issue by Madeorsk** [Plume-org/Plume#74]
I don't like the term "reshare". I understand that the idea behind this word is to say that we share a second time, but I think that a second share should still be named a "share".

We use the word "Publish" in the button to create a new blog post, why not using this word again and rename "reshare" to "republish"?

**Comment by zcdunn** [comment]
At the risk of starting a long bikeshed, I'd like to suggest 'boost' as the alternative. When you share an article somebody has written, you're boosting its visibility and it sounds less technical than republish or share

**Comment by BaptisteGelez** [comment]
I really like the idea that "boost" conveys, it doesn't feel like you are "stealing" someone else work.
