### ISSUE TITLE
[FAQ] Question: Plume vs Rustodon?

### ISSUE THREAD

**Issue by cypherbits** [Plume-org/Plume#740]
I have a question: Plume vs Rustodon (https://github.com/rustodon/rustodon/)?
Differences about features?

**Comment by MasterOfTheTiger** [comment]
Rustodon is a microblogging platform. In addition, it seems to be in its earlier stages than Plume.

**Comment by marek-lach** [comment]
> I have a question: Plume vs Rustodon (https://github.com/rustodon/rustodon/)?
> Differences about features?

Plume is _NOT_ a micro-blogging server. It is rather a blogging platform similar in spirit to Medium.com, Svbtle.com, or Write.as, just with federation. It is intended for longer articles than Mastodon, Pleroma, or Rustodon.

**Comment by cypherbits** [comment]
Thanks for the answers. Sometimes you find similar projects and you can't see their differences just by reading their Readme. This simple question is important. 

Tip: write the answer on the project Readme, please.

**Comment by MasterOfTheTiger** [comment]
I think these make it fairly clear:

> Plume is a federated blogging engine, based on ActivityPub.

> A blog-centered approach 

While Rustodon's README explains that it is a micro-blogging platform.
