### ISSUE TITLE
Mobile menu issues

### ISSUE THREAD

**Issue by dixonge** [Plume-org/Plume#75]
Platform: iOS
Browsers: Firefox, Safari
Expected behavior: Menu button should do something
Actual behavior: Menu button does not do anything

This is in portrait mode. When turned sideways, the full header appears, revealing the logo/home/login/register links.

**Comment by BaptisteGelez** [comment]
Thanks for the report, I personally don't own an iPhone to test, but we will try to figure this out.

**Comment by dixonge** [comment]
FYI, when I shrink my desktop Firefox small enough to trigger the CSS changing over to mobile view, the Menu works as expected. May be limited to touch/tap functions?

**Comment by BaptisteGelez** [comment]
I think it is an issue with the rendering engine used by browsers on iOS, because it works fine with Firefox on my Android phone.

**Comment by BaptisteGelez** [comment]
@dixonge The mobile menu has been updated, could you try it again on https://baptiste.gelez.xyz please, and tell me if it works now?

**Comment by BaptisteGelez** [comment]
It has been confirmed that it still doesn't work with the new menu.

**Comment by BaptisteGelez** [comment]
It also affects Chrome mobile (version 44)

**Comment by dixonge** [comment]
Still nothing :(
