### ISSUE TITLE
Cannot like nor boost at remote instance

### ISSUE THREAD

**Issue by KitaitiMakoto** [Plume-org/Plume#755]
Hi,

Sorry for reporting and pull-requesting almost daily. I realize you have your life and now COVID-19 might threaten your(and our) life. I don't remind at all even if you take a long time to respond to me.

BTW, I found that we cannot like nor boost blog posts at remote instances.

1. Assume I'm `KitaitiMakoto@blogs.kitaitimakoto.net` and reading a remote blog post `https://fediverse.blog/~/Vinyll/future-proof-web-components`.
2. That's good article. I want to like it and push like button.
3. I'm navigated to `https://fediverse.blog/~/Vinyll/future-proof-web-components/remote_interact`.
4. There are two choices : A) logging in to fediverse.blog and continuing to like it, or B) liking it from another instance.
5. I choose B, enter `KitaitiMakoto@blogs.kitaitimakoto.net` into a form input, and submit it.
6. I'm navigated to `POST https://fediverse.blog/~/Vinyll/future-proof-web-components/remote_interact`
7. I'm redirected to `https://blogs.kitaitimakoto.net/remote_interact?https://fediverse.blog/~/Vinyll/future-proof-web-components/`.
8. I see "We couldn't find this page." error.

After that, I can like it by changing the URI to `https://blogs.kitaitimakoto.net/remote_interact?target=https://fediverse.blog/~/Vinyll/future-proof-web-components/` at web browser's address bar manually(`target=` is inserted).

Fixing redirect URI to have `target=` seems good but deploying fixed version to all instances over the world is impossible. This is a difficult issue. It might be good to redirect requests without `target=` to correct URI at `blogs.kitaitimakoto.net` as well as fixing redirect URI at `fediverse.blog`.

And documenting the spec might be helpful for the future-proof.

- **Plume version:** You can find it in the footer of your instance. If you know the exact commit, please also add it.
  - ac7a05b for blogs.kitaitimakoto.net
  - 0.4.0 for fediverse.blog
- **Operating system:**
  - Windows 10
- **Web Browser:**
  - Firefox

**Comment by elegaanz** [comment]
> Sorry for reporting and pull-requesting almost daily.

No problem, it is great to see someone motivated to work on Plume (by the way if you want push access to the repo to make your workflow simpler, I can give you the rights).

> I realize you have your life and now COVID-19 might threaten your(and our) life

COVID-19 is not really a threat to me, to be honest. But I stopped working on Plume myself, and I would like to find a new maintainer, that's why I may seem not so active… sorry about that.

And for the bug, it is the responsibility of the instance admin to update their instance. Maybe it will never be fixed everywhere, but we should not stop ourselves because of that.

**Comment by KitaitiMakoto** [comment]
Thank you for the reply.

> Maybe it will never be fixed everywhere, but we should not stop ourselves because of that.

I agree with you. We should not stop. I think there are two choices:

* Fixing this issue by **ONLY** inserting `target=` to redirect URI in response from `POST /~/Vinyll/future-proof-web-components/remote_interact`. In this case, liking and boosting posts on instances under current version keeps this problem while code remains simple.
* Fixing this issue by inserting `target=` to redirect URI in response from `POST /~/Vinyll/future-proof-web-components/remote_interact` **AND** having `/remote_interact` accept parameter without `target=` such as `/remote_interact?https://fediverse.blog/~/Vinyll/future-proof-web-components/`. This fixes Plume federation network even if all instances are not updated but code should be complex(actually, I don't know it is possible for Rocket framework).

This is what I wanted to say by "this is a difficult issue". People who fix the problem and maintain Plume should decide which is better. I just show choices(If I send a pull request, of course I choose one).

---

> by the way if you want push access to the repo to make your workflow simpler, I can give you the rights

Thank you so much, it's an honor! However I'd prefer to create pull requests even if I have write access permission because of two reasons that other people's eyes are important to find my mistakes and that I'm not good at Rust programming. For the reasons, my workflow regarding writing code and sending pull requests will not change if I have access right. But...

>  I stopped working on Plume myself, and I would like to find a new maintainer, that's why I may seem not so active… sorry about that.

Not at all, you don't need feel sorry. I respect your decision. It's okay. For now, I cannot offer to be a successor because I don't have enough time, I don't have enough Rust skill and I don't understand Plume concepts well. What I might be able to help you are reviewing non-difficult pull requests and discuss on issues. As doing them, I will be able to learn Rust and Plume. If you feel it's good, could you give me access right? Additionally, I appreciate if you give me Proofreader role on Crowdin ;)

**Comment by KitaitiMakoto** [comment]
I confirmed I was given Proofreader role on Crowdin! Thank you very much.

**Comment by KitaitiMakoto** [comment]
This issue was fixed by #762.
