### ISSUE TITLE
clang dependency missing in Dockerfile.dev

### ISSUE THREAD

**Issue by koalp** [Plume-org/Plume#763]
A debian dependency seems to be missing in the Dockerfile.dev. I can't build the image without adding clang to the installed here :
https://github.com/Plume-org/Plume/blob/73aa301d4a17953e3437ba3c6d5d6f252ac3b5f2/Dockerfile.dev#L3

So I think the clang package should be added to this dockerfile.
Another solution could be to merge the dev Dockerfile with the Dockerfile by adding the RUN command to the build step.

Also, as a sidenote, as the Dockerfile extension is used to trigger syntax highlighting in some text editors, it could be nice to rename Dockerfile.dev to dev.Dockerfile.

**Comment by KitaitiMakoto** [comment]
It seems a good point. I checked diff between Dockerfile and Dockerfile.dev:

```diff
--- Dockerfile	2020-04-12 07:04:04.988530800 +0900
+++ Dockerfile.dev	2020-04-07 02:46:09.335750300 +0900
@@ -1,4 +1,4 @@
-FROM rust:1-stretch as builder
+FROM rust:1-stretch
 
 RUN apt-get update && apt-get install -y --no-install-recommends \
     ca-certificates \
@@ -10,8 +10,7 @@
     gcc \
     make \
     openssl \
-    libssl-dev \
-    clang
+    libssl-dev
 
 WORKDIR /scratch
 COPY script/wasm-deps.sh .
@@ -19,6 +18,7 @@
 
 WORKDIR /app
 COPY Cargo.toml Cargo.lock rust-toolchain ./
+RUN cargo install diesel_cli --no-default-features --features postgres --version '=1.3.0'
 RUN cargo install cargo-web
 
 COPY . .
@@ -28,19 +28,6 @@
 RUN cargo install --path plume-cli --force --no-default-features --features postgres
 RUN cargo clean
 
-FROM debian:stretch-slim
-
-RUN apt-get update && apt-get install -y --no-install-recommends \
-    ca-certificates \
-    libpq5 \
-    libssl1.1
-
-WORKDIR /app
-
-COPY --from=builder /app /app
-COPY --from=builder /usr/local/cargo/bin/plm /bin/
-COPY --from=builder /usr/local/cargo/bin/plume /bin/
-
 CMD ["plume"]
 
 EXPOSE 7878
```

The seems no need to use Dockerfile.dev. Now we can run database migration by `plm migratin run` and `redo` commands.

If you need more operations by `diesel` command, of course we can embed it into Docker image.

**Comment by koalp** [comment]
I don't have usage for diesel_cli in the image yet. I used it for deployment of test instances, but the non-dev image serve this purpose too.
