### ISSUE TITLE
remove dependency on runtime-fmt

### ISSUE THREAD

**Issue by jebrosen** [Plume-org/Plume#769]
(This came out of a discussion on IRC)

`runtime-fmt` uses perma-unstable rust APIs and is therefore susceptible to breakage (e.g. SpaceManiac/runtime-fmt#13, #674)

As far as I can tell, `rt_format!` is much more powerful than necessary and `src.replace("{uri}", replacement)` would work in both places it is used. `str::replace()` does not support formatting instructions such as `{uri:<100}`, so it's not a drop-in replacement. My guess is that only the literal `{uri}` actually needs to be replaced, though.

**Comment by igalic** [comment]
from what i understand, removing it from Plume should be easy.
Removing it from gettext-macros might be a bit harder…

**Comment by elegaanz** [comment]
A first version of gettext-macros was using a custom macro for formatting (that @fdb-hiroshima wrote IIRC), it could be possible to re-introduce it.

**Comment by fdb-hiroshima** [comment]
I did wrote such a macro, but I'm not sure we actually used it. Still we use a very small part of what format! allow, having a macro supporting in order `{}`, indexed `{0}` and named `{name}` is in the realm of possible

**Comment by igalic** [comment]
anyway, would someone who knows how `rt_format!()` works mind posting a patch / pull request for the two current uses in our own code base?
