### ISSUE TITLE
activitypub activities lack required to/cc/id fields

### ISSUE THREAD

**Issue by kaniini** [Plume-org/Plume#77]
subject covers it.

in the case of new posts being created, the objects have the to/cc fields instead of the activities themselves.  this causes pure activitypub message routers like pleroma to discard the activity as invalid, since the activity lacks the to/cc fields.

also, in all cases, an activity must have an id.  for example, the accept responses plume sends lack an id field.

**Comment by kaniini** [comment]
other than this, Pleroma presently doesn't detect any major federation protocol violations, but i can't test any further until the to/cc are fixed, I suppose.

**Comment by BaptisteGelez** [comment]
Does Pleroma support the `Article` type? (and thanks for the reports btw)

**Comment by kaniini** [comment]
my testing instance does have awareness of `Article` items, but it's not enabled in mainline quite yet because nobody was using it.  we treat them the same as notes, since pleroma will autocollapse any data larger than 1KB.

**Comment by BaptisteGelez** [comment]
All activities should have these fields now. And the demo instance has been updated if you want to check.
