### ISSUE TITLE
There is no 0.4.0 release?

### ISSUE THREAD

**Issue by matthiasbeyer** [Plume-org/Plume#779]
In your blog you [write that plume 0.4.0 is out](https://fediverse.blog/~/PlumeDev/plume-0.4.0-is-out) but there is no tag in the repository.

Please provide one.

**Comment by fdb-hiroshima** [comment]
Tag is actually `0.4.0-alpha-4`

**Comment by matthiasbeyer** [comment]
So the blog article is wrong because there is no 0.4.0 release yet?

**Comment by elegaanz** [comment]
"alpha-4" is an "alias" for 0.4, sorry if it is confusing. 😅

**Comment by matthiasbeyer** [comment]
How come? "0.4.0-alpha-4" is clearly not "0.4.0", it is still an alpha release before the actual 0.4.0 release is out.

At least that's what a user would expect. After the 0.4.0-alpha-4, I would either expect 

* a 0.4.0-alpha-5
* a 0.4.0-beta-1
* or a 0.4.0

release!

**Comment by matthiasbeyer** [comment]
Whut? Now that I had a closer look on the release page, it is even more confusing!

Basically, you released no version yet. You went from

"0.2.0-alpha-1" (which really should be "0.1.0-alpha.1") to
"0.3.0-alpha-2" (which really should be "0.1.0-alpha.2") to
"0.4.0-alpha-4" (which really should be "0.1.0-alpha.3").

So you did not only jump to "0.4" without ever releasing "0.1.0", "0.2.0" or "0.3.0", you even did jump to "0.4.0-alpha-4" without ever releasing "0.4.0-alpha-{1,2,3}"...

So basically it is double-counter-intuitive. 

Although semver explicitely states that 0.y.z releases should not be considered stable and everything might happen, packeteers and users are confused and if they only see that there's a "0.4.0-alpha-anything" that there already is a 0.3.0 release they might test. Ugh.

---

Well, I'm not sure where to go from here. What is the right thing to do now? Deleting tags is strongly discouraged, so it is not an option and might break experiemental deployments all over the place (essentially breaking users deployments by vanishing... not a good thing)!
So all you could do is make the next release 0.4.0 and then start following semver properly from there. Everything else is just too confusing for users, packaging people (which is my role in this) and everyone else.

So that's my suggestion: Release 0.4.0 as soon as you're comfortable with the code being ready, then follow semver and make the next releases 0.5.0, 0.6.0 and so on!

---

Hope you're not discouraged by this issue from releasing your code! I really hope that I can use plume myself one day and I'm really looking forward to that day! Happy hacking! :smiley:

**Comment by elegaanz** [comment]
I must admit that this versioning is not 100% semver-compliant… :sweat_smile: Maybe we should indeed just use `0.5.0`, `0.6.0`, etc, for future releases.

**Comment by elegaanz** [comment]
We just published Plume 0.5.0, without any suffix in the tag name. We will follow this scheme from now. I hope this fixes your issue.

**Comment by matthiasbeyer** [comment]
:tada: awesome!
