### ISSUE TITLE
Adding font for Persian language

### ISSUE THREAD

**Issue by DearRude** [Plume-org/Plume#783]
Unfortunately, when you write in Persian language, the default system font will be displayed. Despite English, it's very unreadable with Persian.

I suggest using [Shabnam Font](https://github.com/rastikerdar/shabnam-font) for Persian interface and [Vazir Font](https://github.com/rastikerdar/vazir-font) for blogposts.
Vazir Font is a open-source font which is used in default in Mastodon, OpenStreetMap and Telegram for Persian/Arabic. It is also widely used in Persian blogging websites such as [Virgool](https://virgool.io/).

**Comment by elegaanz** [comment]
I don't know exactly how we can load a different font depending on the language… Maybe we could add a `lang="xx"` to `<html>`, and then do something like :

```css
html[lang="fa"] {
    font-family: "Shabnam";
}
```

Anyway, thank you for your fonts suggestions!

**Comment by DearRude** [comment]
I don't think if we can use a lang keyword for CSS fonts or not. However, based on what I saw on other websites, they use [Vazir WOL](https://github.com/rastikerdar/vazir-font/tree/master/dist/Farsi-Digits-Without-Latin) (without latin) in priority - so text triggers Vazir if Persian or iterates to the next font if not. 

I believe there is another way to specify a `unicode-range` when declaring Persian font so it only triggers certain characters.

**Comment by theMasix** [comment]
#787

**Comment by elegaanz** [comment]
I think we can close this issue, thanks to #787
