### ISSUE TITLE
Add a uniqueness constraint on the ap_url field

### ISSUE THREAD

**Issue by BaptisteGelez** [Plume-org/Plume#79]

**Comment by murrayjbrown** [comment]
I presume what's needed here is some way to disambiguate multiple instances on a domain, right? In which case this should be simply achieved by establishing an instance-specific path prefix; i.e., assuming instance names are unique, in _plume-models/src/instance.rs:_

```rust
pub fn compute_box(&self, prefix: &'static str, name: String, box_name: &'static str) -> String {
    ap_url(format!(
        "{instance_domain}/{instance_name}/{prefix}/{name}/{box_name}",
        instance_domain = self.public_domain,
        instance_name = self.name,
        ...
    ))
}
```

Or rather, is the goal to ensure that the local instance name does not conflict with a remote one?

**Comment by BaptisteGelez** [comment]
@murrayjbrown sorry for the late reply, but that's not exactly the problem here: by adding this constraint, we would be sure we never store the same activity more than once.

**Comment by murrayjbrown** [comment]
@BaptisteGelez This issue, then, is impropertly stated. The constraint should be placed, rather, on the uniquess of an activity identifier, which is just a part of what comprises a URL. (I had previously assumed such a basic constraint would have been implemented.)
