### ISSUE TITLE
Version number 0.5.0 not updated in footer

### ISSUE THREAD

**Issue by Wivik** [Plume-org/Plume#791]
Hello,

I've updated my Plume instance pulled from docker image to install the 0.5.0 but the footer still indicates 0.4.0.

I have the new features on the GUI described in releas note, so I think it's just a variable somewhere that was not updated in code ? (sorry, I don't know where)

- **Plume version: should be 0.5.0** 
- **Operating system: CentOS 8**
- **Web Browser: Vivaldi latest stable**

**Comment by igalic** [comment]
yupp, and that's what #789 / #790 are for

**Comment by Wivik** [comment]
I missed these issues while searching, my bad :)

I close this one.
