### ISSUE TITLE
Add version 0.5.0 on Docker Hub

### ISSUE THREAD

**Issue by Chostakovitch** [Plume-org/Plume#795]
Hello folks,

First of all, thanks for this amazing release. :)
We use a customized image based on the one published on Docker Hub, and to be reproducible we never use the latest tag.

The 0.5.0 tag is not yet available on Docker Hub. If someone has the time to fix it, thanks in advance!

**Comment by elegaanz** [comment]
Here it is: https://hub.docker.com/layers/plumeorg/plume/v0.5.0/images/sha256-333cf979175f60196559854a04ff44ba5a16683fa3a97cc6fd71bda5f85c3b02?context=repo
