### ISSUE TITLE
Switch final Docker image to Buster

### ISSUE THREAD

**Issue by Chostakovitch** [Plume-org/Plume#796]
Hello everyone,

We use a customized version of the official Plume Docker image.
When building an image, we perform a few security analysis, for example to detect critical CVE inside the image.

There is a lot of unfixed High CVE in Debian Stretch (see `stretch.log` attached : 91 CVE, 8 classified as high)
By switching from `stretch-slim` to `buster-slim` [here](https://github.com/Plume-org/Plume/blob/28576c1fa3ce5f3259952faa8af1ca1647aedaa5/Dockerfile#L31), the CVE number is lower. (see `buster.log` attached : 60 CVE, 2 classifed as high).

I made a few tests with Buster without noticing any problem.

I think that switching from Stretch to Buster in the final image (the builder is not that important) would be a good thing.
However I don't know if it could be a bias due to packages in Buster being newer, so with less CVE detected (but I don't think so).

Have a nice day :)

[buster.log](https://github.com/Plume-org/Plume/files/4860224/buster.log)
[stretch.log](https://github.com/Plume-org/Plume/files/4860225/stretch.log)

**Comment by igalic** [comment]
there's probably no harm in updating both

do you wanna provide a patch?

**Comment by Chostakovitch** [comment]
Sure, see #797.

I checked that the compilation works on my system, I hope it's all good. :)
