### ISSUE TITLE
Remove local users from target list before sending activities

### ISSUE THREAD

**Issue by BaptisteGelez** [Plume-org/Plume#80]
Else, we send requests to our own instance and end up with duplicated content.

**Comment by kaniini** [comment]
you should use the followers collection for this.

**Comment by BaptisteGelez** [comment]
Yes, this is what we are doing, but this collection may contain local followers as well I think, so we should filter it before sending the activity.

**Comment by kaniini** [comment]
well, the messages i get from plume have specific URIs in them, which results in replies having a bunch of people tagged on them.
