### ISSUE TITLE
Do not support search in Chinese

### ISSUE THREAD

**Issue by pullopen** [Plume-org/Plume#803]
Hello, Thank you for developing this wonderful software! I tried to write a blog article in Chinese. But when I search my title or my tag in Chinese in search bar, it does not show any content. I wonder if it's because it still does not support searching in Chinese? Anyway I sincerely hope it will be supported someday!

**Comment by trinity-1686a** [comment]
I don't speak a single world of Chinese, but I *think* it works. Searching by title can be seen [here](https://fediverse.blog/search?q=%E6%88%91%E4%BB%AC%E7%94%9F%E6%9D%A5%E4%B8%8D%E5%B1%9E%E4%BA%8E%E4%BB%80%E4%B9%88%E5%9C%B0%E6%96%B9), and by tags [there](https://fediverse.blog/search?q=%E8%BE%89%E5%8E%9F%E6%9E%9C%E6%B1%81).

Indexing documents for search is best done batched (indexing 10 documents is not much longer than indexing 1), so Plume only update it's search index every 30 minutes or so. That might be what you saw.

**Comment by igalic** [comment]
not even with https://github.com/Plume-org/Plume/pull/776 ?

**Comment by pullopen** [comment]
I tried again and I think it's just because I didn't wait long enough. Now I can see my article.
Thanks for answering!
