### ISSUE TITLE
Try to update to v0.5.0 in docker and failed in migration

### ISSUE THREAD

**Issue by pullopen** [Plume-org/Plume#804]
I followed the step to install Plume with docker and it all went well. Then I tried to update it to v0.5.0. But when I tried to run:
`docker-compose run --rm plume plm migration run`

The output shows:
```
Configuration read from /app/.env
thread 'main' panicked at 'Couldn't connect to the database.: BadConnection("could not translate host name \"postgres\" to address: Name or service not known\n")', plume-cli/src/main.rs:37:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Is it because I set up a wrong address in my `.env` file? I didn't change things much in the `postgres://` line except the "passw0rd".

- **Plume version: v0.4.0 
- **Operating system: Ubuntu 18.04

**Comment by igalic** [comment]
does your username, password or hostname perhaps contain "special" characters?
anything that would be encoded in an URL?

**Comment by KitaitiMakoto** [comment]
Cannot you connect to PostgreSQL container from Plume container as error message says? You can check it by:

    % docker-compose exec --rm plume bash
    # apt install iputils-ping
    # ping postgres

Do packets from `ping` reach postgres?

If no, docker-compose network might be broken although I don't know how to fix other than recreating containers.

**Comment by igalic** [comment]
oh, somehow i missed the docker part (the part i know nothing about)

**Comment by cybergipsy2020** [comment]
I have the same error message when I tried to update. I tried `ping postgres` and got a error message `ping: postgres: Temporary failure in name resolution`.

**Comment by cybergipsy2020** [comment]
I went digging and found that `/var/lib/postgresql/data` (in `docker-compse.yml`) doesn't exist, but there's `/var/lib/postgresql/10/main` (, `10` being the version of postgresql). I tried to change the `volumes: - "./data/postgres:/var/lib/postgresql/10/main"` line in `docker-compse.yml`, but it doesn't seem work.

**Comment by igalic** [comment]
try pointing out to `/var/lib/postgresql/10`, since `main` is already part of the data

to me, this sounds like a regression in the way that container is built.
but they probably did this on purpose, so you can… intuitively… do something.

**Comment by pullopen** [comment]
Problem solved. It would report failure if you run the migration code **after** you run `docker-compose down` as written in document. You should run `docker-compose up -d` first then `docker-compose run --rm plume plm migration run`, then it will work. 

I think it's a mistake in the document?
