### ISSUE TITLE
[Suggestion] Add Textile language support, alongside Markdown

### ISSUE THREAD

**Issue by marek-lach** [Plume-org/Plume#805]
**What is it?**
a markup language (like Markdown) for formatting text in a blog or a content management system (CMS).
https://textile-lang.com/

**Why**
Since the visual editor isn't really ideal yet, extending the functionality of the primary, markup editor could be an option for added flexibility during writing.

**Priority**
Low. Not a necessity, more a nice-to-have.

**A parser for rust, and syntax renderer into HTML**
https://docs.rs/textile/0.2.1/textile/parser/index.html

https://docs.rs/textile/0.2.1/textile/

**Comment by igalic** [comment]
this would be trivial* to the backend:

- extend database scheme to include post format
- migrate current posts to markdown
- add textile as dependency
- make the current parser "generic"
- choose the correct parser based on the post format

but this also needs work in the fronted, and i have no idea what that entails, especially in the new editor, but most likely, we'll need a JavaScript library for generating textile previews

____
*for definitions of trivial, which might actually be extremely overwhelming

**Comment by marek-lach** [comment]
> most likely, we'll need a JavaScript library for generating textile previews

is this it? https://github.com/borgar/textile-js
