### ISSUE TITLE
How to add my own instance to the site list ?

### ISSUE THREAD

**Issue by stemy2** [Plume-org/Plume#814]
Hello,

I created my own instance, but i don't know how to add it to the offical site. Could you explain how to do it ? Thanks.

**Comment by elegaanz** [comment]
Hello, you can make a PR [to this file](https://git.joinplu.me/plume/joinplu.me/src/branch/main/source/javascripts/instances.json) (we moved to our own Gitea). Or you can just give us the required info and we will add it for you (name, URL, and short description).

Thank you for using Plume, btw!

**Comment by stemy2** [comment]
OK, the full description is here below.

Name: StemyPlume
URL: plume.stemy.me
Description: Instance pour mon usage personnel, mais accessible à qui veut.

**Comment by igalic** [comment]
i think a general presence or at least availability in our matrix channel would also be a good idea for when people come in and ask who the admin is, if something goes wrong with the instance ;)

it's also a good way to keep up with our current development and our future plans

**Comment by elegaanz** [comment]
I added you! https://git.joinplu.me/plume/joinplu.me/src/branch/main/source/javascripts/instances.json#L75-L77

I'm going to update the website so that you appear here. I'm closing this issue.
