### ISSUE TITLE
Dead Matrix Links

### ISSUE THREAD

**Issue by conor-f** [Plume-org/Plume#819]
[Disroot are turning off their Matrix instance](https://disroot.org/en/blog/time-to-switch-some-lights-off) it seems and their homeserver is no longer accessible rendering all the links dead and no clear way to look for help/discussion on plume.

I've seen it in a good few places - the README of this repo and on the website with the "Chat Room" link. I'd open a PR instead of an issue but I don't want to just remove it and not replace it with the correct place to contact everyone.

**Comment by KitaitiMakoto** [comment]
Thank you for the information! I fixed it.
