### ISSUE TITLE
Add blog.anartist.org instance

### ISSUE THREAD

**Issue by Porrumentzio** [Plume-org/Plume#820]

**Comment by FreyjaWildes** [comment]
What is the actual subject of this ? It seems it has nothing to do with an issue (bug, feature request) for the projet.
Please provide further details

**Comment by Porrumentzio** [comment]
This was a petition to add that instance in joinplu.me, where there are some other instances listed.

**Comment by KitaitiMakoto** [comment]
I've done: https://joinplu.me/

@Porrumentzio Thank you for informing us.

@FreyjaWildes Thank you for helping us.

**Comment by KitaitiMakoto** [comment]
@FreyjaWildes 
You may tell us about your intance by filing a issue or sending a pull request against this file: https://git.joinplu.me/plume/joinplu.me/src/branch/main/source/javascripts/instances.json (GitHub mirror: https://github.com/Plume-org/joinplu.me/blob/main/source/javascripts/instances.json)

> Also: I wish to participate to the code

Do you mean you wish to edit instance list by code? If so, send a pull request to [joinplu.me](https://git.joinplu.me/plume/joinplu.me) I said above! If you mean source code of Plume application, always welcome pull requests!
