### ISSUE TITLE
Spaces get removed from tags

### ISSUE THREAD

**Issue by ahangarha** [Plume-org/Plume#825]
There are many cases in which (at least in Persian language) a tag may include space(s). Currently, Plume removes space from tags. Look at the following screenshots to see what is entered as tag and how it is damaged in output;

![image](https://user-images.githubusercontent.com/11241315/98542313-558eae00-22ae-11eb-9d18-aa5ba39279c0.png)

![image](https://user-images.githubusercontent.com/11241315/98542349-663f2400-22ae-11eb-8abd-05bebe43a9cd.png)

- **Plume version:** 0.4.0

**Comment by KitaitiMakoto** [comment]
@ahangarha  In English, it is acceptable to convert "Hello World" to a tag "HelloWorld" though it's a slightly strange. In Persian, it's not acceptable, right? Let me know because I don't know about Persian language at all.

**Comment by ahangarha** [comment]
Yes. It is not working for Persian.

در تاریخ یکشنبه ۲۲ نوامبر ۲۰۲۰،‏ ۱۱:۵۴ KITAITI Makoto <
notifications@github.com> نوشت:

**Comment by KitaitiMakoto** [comment]
Okay. Currently, Plume doesn't detect language so the same rules are applied to all posts. I will try to keep spaces in tags but it will take long time because it will introduce breaking changes and we need check carefully.

**Comment by KitaitiMakoto** [comment]
Development note: My idea is to use `to_title_case` instead of `to_camel_case`

**Comment by elegaanz** [comment]
Tags can be kept as they are specified I think, many people have requested that Plume stop modifying their tags, and I don't see any good reason we should add uppercase letters at the beginning of words with title case, some people will probably still be upset about it.

**Comment by ahangarha** [comment]
See! There is no camel case or upper case or any other case in Persian,
Arabic, Urdu, Kashmiri, Pashto,...

Either it should be allowed to add underscore (similar to hashtags) or let
people add space if needed. I think allowing space is far better.

در تاریخ یکشنبه ۲۲ نوامبر ۲۰۲۰،‏ ۱۴:۵۳ KITAITI Makoto <
notifications@github.com> نوشت:

**Comment by KitaitiMakoto** [comment]
Fixed by https://git.joinplu.me/Plume/Plume/pulls/832 . Could you wait for next release?

**Comment by ahangarha** [comment]
No hurry. Thank you for making the change. I really appreciate.

در تاریخ یکشنبه ۲۲ نوامبر ۲۰۲۰،‏ ۱۹:۵۲ KITAITI Makoto <
notifications@github.com> نوشت:

**Comment by ahangarha** [comment]
Great. Today I saw this change is live on fediverse.blog.

Just I noticed another issue: exclusion of underscore from tags (and hashtags). In Persian, if some hashtag is long, we use _ instead of space. This is an example: #نرم‌افزار_آزاد which has both ZWNJ between نرم and افزار and it as underscore between them and آزاد. Now, underscore is automatically removed from tags and hashtags..

**Comment by KitaitiMakoto** [comment]
It should be fixed with this issue together.

**Comment by KitaitiMakoto** [comment]
These issues should be fixed in version 0.6.0. Can you check it out?

**Comment by ahangarha** [comment]
Thanks. It is working well.
