### ISSUE TITLE
Minor: reported version  number is wrong in 0.5.0

### ISSUE THREAD

**Issue by FreyjaWildes** [Plume-org/Plume#827]
`plm --version` and `plume --version` report version number 0.4.0 instead of 0.5.0 in latest relase (0.5.0 as of writing).

- **Plume version: 0.5.0** You can find it in the footer of your instance. If you know the exact commit, please also add it.
- **Operating system: Ubuntu/Debian**
- **Web Browser: N/A**

**Comment by KitaitiMakoto** [comment]
Thank you for reporting. We missed bumping version at last release. It will be fixed next release.

**Comment by iamdoubz** [comment]
If you are the admin, you can add one of the pull requests manually and it will correct the version number for 0.5.0. As of writing, only one server has done this... mine 😄 

![plume_050](https://user-images.githubusercontent.com/4871781/101206363-a63ac200-3634-11eb-874e-34f36b1926ea.png)

**Comment by KitaitiMakoto** [comment]
This was fixed in 0.6.0.
