### ISSUE TITLE
Add writers to a blog

### ISSUE THREAD

**Issue by 1-byte-man** [Plume-org/Plume#828]
Hi, I'm making a blog with some friends and after creating it we don't know how to add people to it. We've seen the blog configuration and the profiles of the people we wanna add but there's nothing about adding them as writers to the blog. The Plume instance that we are using is [Fediverse Blog](https://fediverse.blog) and the version running on the instance is 0.4.0

**Comment by KitaitiMakoto** [comment]
@1-byte-man Thank you for using Plume.

Currently, you cannot write a single blog by multiple authors, though we have plan to implement the feature. Sorry for inconvenience.

**Comment by KitaitiMakoto** [comment]
And this is the same to #774. I will close this.

(I want to work with this feature after current stuffs completed.)
