### ISSUE TITLE
Anyway to inhance character limit?

### ISSUE THREAD

**Issue by pullopen** [Plume-org/Plume#831]
**Is your feature request related to a problem? Please describe.**
There's character limit set in Plume, which is around 131072 characters. However, when I type Chinese, one Chinese character can occupy 9 characters in Plume, resulting into an actual limit around 14562 Chinese characters. A short novel can easily exceed it. 

**Describe the solution you'd like**
A way for administrator to modify or inhance the character limits.

**Describe alternatives you've considered**
Or would you please tell me where can I modify the code to inhance the character limit? Since I'm totally a beginner and not know anything about Rust.

**Additional context**
A easier way to modify the character limit in `.env` would be better, but I suppose it would be harder to do?

**Comment by elegaanz** [comment]
You can use the `FORM_SIZE` environment variable (see https://github.com/Plume-org/Plume/blob/main/plume-models/src/config.rs#L42). I don't know if it is documented tho, maybe it is missing from the docs?

**Comment by pullopen** [comment]
> 
> 
> You can use the `FORM_SIZE` environment variable (see https://github.com/Plume-org/Plume/blob/main/plume-models/src/config.rs#L42). I don't know if it is documented tho, maybe it is missing from the docs?

It's definitely not in the document! Thank you very much. I wonder what is "ACTIVITY_SIZE" in the `config.rs` then?

**Comment by elegaanz** [comment]
ACTIVITY_SIZE is the maximum size for an ActivityPub message.

**Comment by pullopen** [comment]
Lovely! Thanks.

**Comment by KitaitiMakoto** [comment]
I added the variables to the documentation: https://docs.joinplu.me/environment/
