### ISSUE TITLE
Missing activation mail at https://git.joinplu.me

### ISSUE THREAD

**Issue by pwFoo** [Plume-org/Plume#835]
Hi,

tried to register at https://git.joinplu.me, but failed because of missing activation mail. Also checked spam folder.
Maybe a mailing problem with gitea instance?

**Comment by trinity-1686a** [comment]
I'm getting mail notifications from gitea, so I guess it works. And we are using the same provider, so it does not really make sens that you received nothing. 
Anyway I've activated your account

**Comment by pwFoo** [comment]
Thanks!

**Comment by Noobao** [comment]
Same thing here and no idea why.
