### ISSUE TITLE
Problems (CSRF, no Styles) with binary install of latest Plume release

### ISSUE THREAD

**Issue by pwFoo** [Plume-org/Plume#836]
Hi,

I downloaded the binaries, configured .env file:
```
DATABASE_URL=/opt/plume/plume.db
ROCKET_PORT=7878
ROCKET_ADDRESS=192.168.178.26
BASE_URL=192.168.178.26:7878
ROCKET_SECRET_KEY=<GENERATED_KEY>
```

Initialized instance
```
./plm migration run
./plm search init
./plm instance new 
./plm users new -n 'admin' -N 'name' -b 'bio' -e 'admin@domain.name' -p 'pass' --admin
```

Now login works fine, but each form post (admin area, ) fails.
```
Ungültiges CSRF-Token
Irgendetwas stimmt mit deinem CSRF token nicht. Vergewissere dich, dass Cookies in deinem Browser aktiviert sind und versuche diese Seite neu zu laden. Bitte melde diesen Fehler, falls er erneut auftritt.

Ungültiges CSRF-Token
```

Site is unstyled?
![image](https://user-images.githubusercontent.com/333408/103572262-91b84680-4ecc-11eb-88af-176772383711.png)

**Comment by trinity-1686a** [comment]
I'm not sure why style is missing, but the CSRF token error is usually caused by using http instead of https

**Comment by pwFoo** [comment]
Thanks. I'll deploy a https instance for testing.

**Comment by pwFoo** [comment]
I think it was dependent to my installation. So I close that issue for now.
