### ISSUE TITLE
Notification do not show in firefox after v0.6.1-dev

### ISSUE THREAD

**Issue by pullopen** [Plume-org/Plume#839]
Notification do not show anymore after v0.6.1-dev in Firefox, while in Chrome it shows normally. Open it and it just turns out as a blank page.

Browser default language is Chinese.

- **Plume version:** v0.6.1-dev
- **Operating system:** Windows 10
- **Web Browser:** Firefox

**Comment by KitaitiMakoto** [comment]
hmm... I couldn't reproduce this problem. Can you tell me git commit hash you built?

> Open it and it just turns out as a blank page.

Did you mean neither Plume logo, title nor page title are shown?

**Comment by KitaitiMakoto** [comment]
@pullopen  There was a bug. It should be fixed at the latest source code and Docker image.
