### ISSUE TITLE
Problem with login

### ISSUE THREAD

**Issue by stemy2** [Plume-org/Plume#840]
I can't login anymore on my instance. A message says "you are now connected", but everything outside this message show clearly that i'm disconnected.

- **Plume version:** 0.4.0
- **Operating system:** Debian
- **Web Browser:** Firefox

**Comment by KitaitiMakoto** [comment]
Did you mean you don't see dashboard, notification, log*out* link and so on?

**Comment by stemy2** [comment]
Yeah, nothing but the message saying "you are now connected".

**Comment by stemy2** [comment]
For some reason, i had to reinstall the app. The problem never happened again. I will reopen if it comes back.

**Comment by KitaitiMakoto** [comment]
Okay, thanks.
