### ISSUE TITLE
Local federation fails

### ISSUE THREAD

**Issue by BaptisteGelez** [Plume-org/Plume#85]
With an `HttpError`. ~~The ports may be removed from the request URL when parsing it.~~

**Comment by fdb-hiroshima** [comment]
Port is fine, the probleme is in `Webfinger::resolve()`, which obtain target url using `WebFinger::url_for_acct()`, which itself only return https urls. The error come from the fact local federation is made with instances supporting only http, and so an ssl error occure before anything is transmited.

**Comment by BaptisteGelez** [comment]
It should be fixed now. You'll have to start your instances with `USE_HTTPS=0` in your environment variables. And you may have to create a new account with HTTPS disabled, since the URL for the ActivityPub representation of the user is computed when registered.

**Comment by fdb-hiroshima** [comment]
this should probably be documented in `DEVELOPEMENT.md`
