### ISSUE TITLE
Please delete all the "space" in article address or it would show error

### ISSUE THREAD

**Issue by pullopen** [Plume-org/Plume#851]
After the recent update, the address of an article will keep the "space" of the title, which will cause error in some circumstances.

If you can delete the spaces and maybe "comma/stops" in the title it would be better. 

- **Plume version:** 0.6.1-dev
- **Operating system:** Windows
- **Web Browser:** Firefox

**Comment by KitaitiMakoto** [comment]
Can you tell details on error which current behavior will cause?

**Comment by pullopen** [comment]
> 
> 
> Can you tell details on error which current behavior will cause?

Especially when it shows in mastodon, if there's a space in the address, the content after the space will not be recogonized as the address.

**Comment by pullopen** [comment]
> 
> 
> Can you tell details on error which current behavior will cause?

For example, the address will show now as "https://plume.pullopen.xyz/~/MyTrash/废墟王子 10" instead of "https://plume.pullopen.xyz/~/MyTrash/废墟王子-10", and the content after the space will not be recogonized as within the address in most circomstances.

**Comment by KitaitiMakoto** [comment]
I'm sorry for very late reply.

I confirmed and realized the problem. I will fix this issue by convert article IRI (includes whitespaces) to URI (percent-encodes them) when sending notification other instances including Mastodon.

**Comment by KitaitiMakoto** [comment]
This is fixed at main branch. But, unfortunately, Docker Hub stopped automated build and there's no Docker image of latest main.

**Comment by pullopen** [comment]
> 
> 
> This is fixed at main branch. But, unfortunately, Docker Hub stopped automated build and there's no Docker image of latest main.

Thanks for that.
