### ISSUE TITLE
URL parsing

### ISSUE THREAD

**Issue by retiolus** [Plume-org/Plume#853]
ex: https://fediverse.blog/~/TreballsUniversitaris/El rol de la dona i l'home en les cançons populars/
should be: https://fediverse.blog/~/TreballsUniversitaris/El%20rol%20de%20la%20dona%20i%20l'home%20en%20les%20can%C3%A7ons%20populars/

![image](https://user-images.githubusercontent.com/65604466/123108236-8a650500-d43a-11eb-9f48-0f7ed09a5c90.png)

URLs are not parsed correctly, there are spaces and not %20 between words.

- **Plume version:** You can find it in the footer of your instance. If you know the exact commit, please also add it.
- **Operating system:**
- **Web Browser:**

**Comment by KitaitiMakoto** [comment]
Same to #851
