### ISSUE TITLE
Long time to build from source code on Pi 4 platform

### ISSUE THREAD

**Issue by erihsu** [Plume-org/Plume#855]
I am trying to build plum from source code on Pi 4 platform , but I have waited for a long time in the front-end building step without any installation feedback. I am not sure if this process stuck by any problem.
```sh
wasm-pack build --target web --release plume-front
```

<img width="547" alt="Screen Shot 2021-09-05 at 11 32 11 AM" src="https://user-images.githubusercontent.com/31060229/132114012-276fdd41-529d-4080-a13d-184a76aee5f3.png">

**Comment by KitaitiMakoto** [comment]
It sometimes takes more than one hour. `top` command might show whether build is stuck or not, though I don't know Pi platform well.

**Comment by erihsu** [comment]
@KitaitiMakoto I can see ```cargo``` process in the ```top``` menu at times with low mem & low cpu usage. But I can't know more about how's going with installation.

**Comment by KitaitiMakoto** [comment]
hmm... it sounds odd. `--dev` flag might shows something helpful:

    wasm-pack build --dev --target web plume-front

**Comment by erihsu** [comment]
> hmm... it sounds odd. `--dev` flag might shows something helpful:
> 
> ```
> wasm-pack build --dev --target web plume-front
> ```

Thx honestly. But I am considering reinstall wasp-pack first on my Pi4 machine 😂. I will keep updating as I got any progress

**Comment by erihsu** [comment]
Finally I found I got stuck by ```rustup``` updating during installation. I have ```rustup update stable``` to meet the minimal rust version requirement in plume tool-chain and hopefully there will be no more stucks.

**Comment by KitaitiMakoto** [comment]
Sounds good
