### ISSUE TITLE
Change like reshare and follow so they are forms

### ISSUE THREAD

**Issue by fdb-hiroshima** [Plume-org/Plume#88]
Currently `like`, `reshare` and `follow` are made through GET requests, however for security reason they should be done through POST request, such as via forms. Can someone try to change those links to forms without breaking current design?
https://github.com/Plume-org/Plume/blob/b26649e8c0d92b5bbf57d69ef5176e1f1667202a/templates/posts/details.html.tera#L43-L56
https://github.com/Plume-org/Plume/blob/b26649e8c0d92b5bbf57d69ef5176e1f1667202a/templates/users/header.html.tera#L22-L26

**Comment by Madeorsk** [comment]
Why use POST instead of GET? CSRF?

**Comment by BaptisteGelez** [comment]
This is the main reason yes, and because it is more correct semantically too.
