### ISSUE TITLE
Can I block a domain from federation?

### ISSUE THREAD

**Issue by pullopen** [Plume-org/Plume#923]
**Is your feature request related to a problem? Please describe.**

I found that my plume site is always flooded with blogs from unrelated domains, which is really redundant to me. Can I add certain domains into blocklist and stop fetching from them? Thank you!

**Describe the solution you'd like**
A viaration in `.env` or control panel to control federation

**Describe alternatives you've considered**
Maybe a config change in nginx?

**Comment by pullopen** [comment]
Oh I saw it in admin control panel, sorry.

**Comment by KitaitiMakoto** [comment]
Plume provides a feature for that. You can see domain list at admin > instances at block using buttons at the page, though a bug that it doesn't work is reported...

**Comment by pullopen** [comment]
> Plume provides a feature for that. You can see domain list at admin > instances and block using buttons at the page,_ though _a bug that it doesn't work is reported...

I'll try to see if it works.
