### ISSUE TITLE
Add SQLite as an option

### ISSUE THREAD

**Issue by skorokithakis** [Plume-org/Plume#93]
Having SQLite as an option would tremendously simplify installation and deployment, increasing adoption. SQLite is an extremely capable RDBMS, it should serve Plume sites very well up to thousands of concurrent visitors.

**Comment by fdb-hiroshima** [comment]
It would also be great to run tests (no need to setup a new database, juste a file). However I don't know how much Diesel (our orm) is database agnostic, it may be a bit challenging to allow both backend.

**Comment by 9034725985** [comment]
The downside is that if diesel is agnostic then it runs into the same problem that SQLAlchemy does in that it can't use any of the more advanced features of postgresql.

**Comment by skorokithakis** [comment]
You can use both for now and decide whether you want to stop supporting SQLite when you actually need the more advanced features. There's also the option of saying "X won't work on SQLite".

**Comment by BaptisteGelez** [comment]
Looking at what have been done for Rustodon may be interesting: https://github.com/rustodon/rustodon/pull/12/

It seems to be possible quite easily.

**Comment by netshade** [comment]
Just wanted to note [this comment](https://github.com/rustodon/rustodon/pull/12#issuecomment-403252679) from our own discussions on SQLite, in case they inform any work you do.
