### ISSUE TITLE
Can not use non-latin as blog name

### ISSUE THREAD

**Issue by pullopen** [Plume-org/Plume#948]
I used to sucessfully create blog with a Chinese name. But recently I found:

1. Try to create a new blog.
2. Can only use latin words or numbers as blog name. Typing Chinese will say "Invalid name".
3. Try to edit existing blog and change name to Chinese. It will respond as a blank page, and not changing the blog name.

Is it on purpose?

- **Plume version:** 0.7.3-dev
- **Operating system:** Windows
- **Web Browser:** Firefox

**Comment by KitaitiMakoto** [comment]
We're sorry. Can you paste sample text so that I can reproduce thos problem on my computer?

**Comment by pullopen** [comment]
> We're sorry. Can you paste sample text_ so _that I can reproduce thos problem on my computer?

For example: 个人博客

Actually I tried Japanese and it still doesn't work.

**Comment by KitaitiMakoto** [comment]
Seems caused by heck upgrading to 0.4.0

**Comment by KitaitiMakoto** [comment]
Thanks!

**Comment by KitaitiMakoto** [comment]
It should be fixed at main branch and latest image. Can you confirm it?

**Comment by pullopen** [comment]
> It should be fixed at main branch and latest image. Can you confirm it?

Yes, it's fixed! Thank you very much!

**Comment by KitaitiMakoto** [comment]
Thanks for your confirmation!
