### ISSUE TITLE
Weird html out on a very long post

### ISSUE THREAD

**Issue by gled-rs** [Plume-org/Plume#96]
See https://plume.mastodon.host/~/Testing1234/how-angry-will-the-admin-get/

We have the csrf token displayed and the end of the post mixed in the comment section.

**Comment by BaptisteGelez** [comment]
I can reproduce, but only if logged in. I think there is an issue with your `rocket_csrf` crate @fdb-hiroshima.

**Comment by fdb-hiroshima** [comment]
I can't get a csrf token being displayed, however I see a nice big block of text repeated like 3 times after the closing </html> tag, so I guess not all browser show this the same way, and this should be enought to try to understand the issue
