### ISSUE TITLE
Slugs can be empty

### ISSUE THREAD

**Issue by BaptisteGelez** [Plume-org/Plume#97]
Making articles unreachable. Try to read the article called :thinking: here: https://plume.mastodon.host/@/test1234/

May be related to #91

**Comment by acrisci** [comment]
Interesting 🤔. What should the slug be for the article called "🤔"?

**Comment by fdb-hiroshima** [comment]
I guess emojis should get striped, and if slug collide or is empty, then tell user to use another title?

**Comment by acrisci** [comment]
> I guess emojis should get striped, and if slug collide or is empty, then tell user to use another title?

Then it is not possible to have articles with a title in Chinese.

**Comment by acrisci** [comment]
Oh nevermind, it's putting the chinese characters in the slug as utf8. That seems like a mistake.

**Comment by acrisci** [comment]
Well actually I think that's ok because wikipedia seems to be putting chinese characters in their urls. 

Yeah maybe we should just give a validation error if the title can't be turned into a slug.

**Comment by BaptisteGelez** [comment]
Fixed by #111
